### ISSUE TITLE
wine-tkg: turn fs{hack,bypass} on by default

### ISSUE THREAD

**Issue by soredake** [Frogging-Family/wine-tkg-git#10]
title

**Comment by sr-tream** [comment]
+1. @Tk-Glitch , what errors can be because of them?

**Comment by Tk-Glitch** [comment]
Well, it's delicate.

1 - It's a big hack
2 - It can break in subtle ways on every daily patch wave
3 - I might not be able to fix it if #2 happens
4 - #2 might already be in action - https://github.com/Tk-Glitch/PKGBUILDS/issues/413
5 - Many people do *not* want it

But then, yes, it's enabled by default in Proton-tkg. I'd say I prefer having a pretty vanilla-y default config for Wine (since Proton is more hacky by nature, and as a result better suited for hacky stuff enabled by default), and leave the users a choice to opt-in for such big patches.

That doesn't mean I'm firmly against it. I'd like to have more feedback :)

**Comment by soredake** [comment]
About fshack problems https://github.com/ValveSoftware/Proton/issues/4091
