### ISSUE TITLE
multiple issues with specific configurations

### ISSUE THREAD

**Issue by aufkrawall** [Frogging-Family/wine-tkg-git#1020]
With this config (preset valve), Battle.Net crashes after installation when it tries to load the log-in button:
[customization.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/11634292/customization.cfg.txt)

With preset staging, only esync (no fsync) is reported when starting Wine:
[customization.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/11634305/customization.cfg.txt)

Applying patches with `_shared_gpu_resources="true"` fails with preset staging:
```
sharedgpures-textures.patch -- ( Applied shared texture resources support patchset )
patching file dlls/winevulkan/make_vulkan
Hunk #4 FAILED at 211.
Hunk #7 succeeded at 1510 (offset 24 lines).
1 out of 7 hunks FAILED -- saving rejects to file dlls/winevulkan/make_vulkan.rej
patching file dlls/winevulkan/vulkan.c
Hunk #12 succeeded at 2048 (offset 48 lines).
Hunk #13 succeeded at 2108 (offset 48 lines).
Hunk #14 succeeded at 2294 (offset 48 lines).
Hunk #15 succeeded at 2321 (offset 48 lines).
patching file dlls/winevulkan/vulkan_private.h
```
[customization.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/11634326/customization.cfg.txt)

Sorry for the annoying report. :frog: 
I hope these things are 100% reproducible, else I'd try to e.g. provide logs.

**Comment by TheComputerGuy96** [comment]
@aufkrawall 1) Can you provide Wine logs for the crash?
2) Have you set WINEFSYNC=1 variable? What kernel do you use?
3) This patchset hasn't been updated for a while and thus it has some conflicts (I'll make a PR for fixing them)

**Comment by aufkrawall** [comment]
> The staging profile is plain staging, which doesn't offer fsync. It has to be patched in, so you need to use a custom profile instead to enable fsync.

Oops, that's a bit embarrassing. With skipped _LOCAL_PRESET prompt, fsync works as expected.

Could narrow down the crash issue with Battle.net client & installer: Seems to happen only with `_protonify="true"`. With the default of false, it installs and runs normally.

**Comment by gabriele2000** [comment]
> Oops, that's a bit embarrassing. With skipped _LOCAL_PRESET prompt, fsync works as expected.

HA! It seems that this tricked you too ahahah!

@Tk-Glitch You might wanna add a hint that selecting a preset will void any customization made, or, well, almost any.

**Comment by gardotd426** [comment]
I was able to fix the `mouse.c` patching error in `proton-tkg-additions.mypatch`, but now it fails because of `wine-tkg-patches/hotfixes/proton_fs_hack_staging/winex11.drv_Ignore_ClipCursor_if_desktop_window_is_foreground.mypatch`.

Commits `397cd1c` and `b750b7` remove the stuff that that patch modifies. Not sure if those lines are even still necessary.

**Comment by gardotd426** [comment]
Removing that patch the patches all apply but the build fails, seemingly because of the battleye stuff. 

Disabling the battleye and eac stuff causes it to fail because for some reason it's force-checking-out commit `07d0f1f0c0b mf/tests: Remove duplicate call to MFStartup().`

That causes it to fail for a bunch of package_id errors which aren't even in the current wine tree:

```
../wine-git/dlls/kernelbase/version.c: In function ‘PackageFullNameFromId’:
../wine-git/dlls/kernelbase/version.c:1754:79: error: ‘PACKAGE_VERSION’ has no member named ‘u’
 1754 |     swprintf(ver_str, ARRAY_SIZE(ver_str), L"%u.%u.%u.%u", package_id->version.u.s.Major,
      |                                                                               ^
../wine-git/dlls/kernelbase/version.c:1755:32: error: ‘PACKAGE_VERSION’ has no member named ‘u’
 1755 |             package_id->version.u.s.Minor, package_id->version.u.s.Build, package_id->version.u.s.Revision);
      |                                ^
../wine-git/dlls/kernelbase/version.c:1755:63: error: ‘PACKAGE_VERSION’ has no member named ‘u’
 1755 |             package_id->version.u.s.Minor, package_id->version.u.s.Build, package_id->version.u.s.Revision);
      |                                                               ^
../wine-git/dlls/kernelbase/version.c:1755:94: error: ‘PACKAGE_VERSION’ has no member named ‘u’
 1755 |             package_id->version.u.s.Minor, package_id->version.u.s.Build, package_id->version.u.s.Revision);
      |                                                                                              ^
make: *** [Makefile:76422: dlls/kernelbase/x86_64-windows/version.o] Error 1
make: *** Waiting for unfinished jobs....
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```

**Comment by aufkrawall** [comment]
`_protonify="true"` still crashes Battle.net with staging 8.11. Looks like every version after 8.5 is affected, that version still works.

**Comment by gabriele2000** [comment]
Now I have this weird problem that after compiling wine is says "no istruction to execute" or something like that, and it doesn't install anything

**Comment by Tk-Glitch** [comment]
Did you enable wow64/nolib32?

**Comment by gabriele2000** [comment]
> Did you enable wow64/nolib32?

wow64 mode, yup

**Comment by Saancreed** [comment]
> `_protonify="true"` still crashes Battle.net with staging 8.11. Looks like every version after 8.5 is affected, that version still works.

@aufkrawall The particular protonify patch that seems to cause this is `ntdll: Guard against syscall stack overrun.`, if you were to remove [a few lines](https://github.com/Frogging-Family/wine-tkg-git/blob/aefe95ebc2b89ab8cb908a3daddd32e3cb05f236/wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/proton-tkg-staging.patch#L3724-L3873) it should work again at least up to Staging v8.9.1 (but I'm also reverting [354a8bb1f4a65bdec052606f2799db9e2907b5b1](https://gitlab.winehq.org/wine/wine/-/commit/354a8bb1f4a65bdec052606f2799db9e2907b5b1) in my builds for another reason) and crash again since Staging v8.10, probably for with different cause this time.

When removing patches to give this a try, don't forget to also update relevant patchset in legacy dir if you're building older release from more recent `master` branch of this repo (e.g. `proton-tkg-staging-af902c1.patch` for Staging v8.9.1).

**Comment by llde** [comment]
@Saancreed I opened a pull request to remove the ntdll stack guard patchset, they broke after the thread stack allocation rework on wine side approximately 2 month ago

**Comment by aufkrawall** [comment]
Thanks, I can confirm that without that patchset, Battle.net launcher installs and runs normally. :)

**Comment by aufkrawall** [comment]
Closing this hence, thx everyone. Only issue I got left is that the options menu of RDR2 goeing wild after some input and temporarily freezes, but likely unrelated separate issue.
