### ISSUE TITLE
World of Warcraft shadowlands beta crashes while trying to connect

### ISSUE THREAD

**Issue by jporterf** [Frogging-Family/wine-tkg-git#104]
running the latest dxvk-bin from the AUR, reinstalled vkd3d, ran it in a clean prefix, wine version is "wine-5.14-132-g1ec8bf9b73 (Staging)"  Crash dumps from wow and build config added as attachments.

[wine-tkg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/5047154/wine-tkg.txt)

[wowcrash.zip](https://github.com/Frogging-Family/wine-tkg-git/files/5047147/wowcrash.zip)

**Comment by gcaliber** [comment]
Have you tried building without the hotfixes?

It seems that wine staging 5.14 does work with wow ptr while other 5.x versions do not, so I'm wondering if it is the reverting patches that break it.

**Comment by SveSop** [comment]
@jporterf 
The crashlog from WoW is not really useful. Could you perhaps post a crashlog from wine?
`WINEDEBUG=+seh,+trace` or something of that nature?

You also write that you use dxvk-bin AND d3d12? If you use dxvk, you have to install it "--without-dgxi" afaik, or else dxgi will not detect d3d12, and WoW is running in d3d11.

**Comment by zurohki** [comment]
I kept crashing in wine-staging 5.14 and my old 5.6 build, but 5.15 is running the beta successfully. Try updating?

**Comment by Thaodan** [comment]
Is this a throwback from #84? I thought the bug was fixed.

**Comment by SveSop** [comment]
I don't think so @Thaodan . I use binutils-2.30, so i should not be "affected" by this (If it is infact the binutils-2.34 thing you are talking about)

**Comment by Thaodan** [comment]
It also had something to do 
with pe-dll build not working.

**Comment by SveSop** [comment]
> It also had something to do with pe-dll build not working.

Not sure what you mean?

**Comment by kenhubcom** [comment]
Any update on this? The normal wine-staging 5.14+ works, but has **a lot** of stuttering. I thought this stuttering might get fixed with fsync enabled, so I tried compiling it myself with wine-tkg. That didn't work and then I found this thread. Still not sure about the cause of the stuttering in wine-staging though, seems to be related with loading stuff from disk.

**Comment by SveSop** [comment]
So far no dice.
I have also seen the rather insane stuttering, but kinda dismissed it cos i am currently running PTR from my HDD and not my NVME drive... And tbh it is a long time since i ran WoW from anything but a SSD or better drive.

The "minimum requirements" listed here: [https://us.battle.net/support/en/article/256565](https://us.battle.net/support/en/article/256565) mentions:

> Hard Disk Drive (HDD)
> 100GB available space (depending on the performance of the drive, player experience may be impacted on HDD) 

Now, this "minimum requirements" DID indicate SSD only, but has been "downgraded" to also include a HDD with the mentioned "player experience may be impacted".
This could suggest that shadowlands maybe have some sort of new technique for loading stuff, and that again (ofc) will make us non-windows users experience something weird.

I dont know, but just flying "around town" on the PTR certainly is a horrible experience for me actually running PTR from a HDD atm... but if the stuttering, albeit perhaps not as bad, also is there when running from a SSD.. maybe there is more to it than that?

It kind of reminds me of what it feels like if you start WoW after you clean up the shader caches, and shaders are being rebuilt and put to disc. As you play more, the stuttering goes away. On PTR it just seems as its "constant" rather than going away over time :)

**Comment by kenhubcom** [comment]
I have it installed on my NVMe, it makes no difference. I also think they have some new technique for loading stuff and it's stuttering because of that. I'm just not knowledgeable enough to debug the exact cause. I tried profiling with sysprof, and the PTR/Shadowlands has a lot of libunwind-related calls, while retail has none. Not sure what that means though.

Do you think I should open a WINE issue so more knowledgeable people could look into it? I'm kind of worried that it won't be fixed until release.

**Comment by Thaodan** [comment]
Better ask at #winehackers on freenode thats the wine development channel.

**Comment by Thaodan** [comment]
Also ask at dxvk if you use that with D3D11

**Comment by SveSop** [comment]
> Also ask at dxvk if you use that with D3D11

It is either dxvk or vkd3d-proton tbh (vkd3d then with d3d12 custom patches for wine-staging from TKG). Using wined3d for d3d11 only runs with WoW set to d3d11-legacy, and is a slideshow at best, so i am pretty sure that is not used :)

It could be loads of additional logging stuff enabled on the WoW client due to it being a beta, and that creates some rather nasty calls in wine even with `WINEDEBUG=-all`, and that it will be turned off at live-launch?
It is not unheard of that dev/beta builds enable loads of extra logging tho.

Opening a ticked for a ptr/beta client might not be looked at in a timely manner anyway, so hitting IRC to see if anyone have some tips would probably be better yeah.

**Comment by SveSop** [comment]
Hmm.. I wonder tho. If Blizzard has turned on additional debugging for the sake of gathering information from the beta/PTR client (highly likely)... could this have something to do with PTR requiring wine-staging > 5.12 aswell?

`--without-unwind` perhaps.... I might do a test-build to see what happens.

If the weird stutter crap would go, it would be perfectly playable without esync/fsync with wine-staging-5.15/5.16 that i have tested so far.

**Comment by SveSop** [comment]
No dice with that "unwind" stuff.. Still stuttering/freezing (somtimes for seconds) flying around places.

There is no huge cpu spikes when that happens, and the gpu load goes way down when it happens. I do believe it has something to do with "loading assets" as blizzard puts it.
Also tested to see if there is a difference with different values of the CVar worldPreloadNonCritical without that having any noticeable effect on anything really.

**Comment by Thaodan** [comment]
Did you try to compare apitrace between live and beta?

**Comment by zurohki** [comment]
On 5.16-staging, the stutter is really terrible while first loading the game, freezing entirely on the loading screen for almost a minute. Once in game, the stutter is very bad but gradually improves over time as more and more game assets are loaded into RAM. After an hour the game is fairly smooth.

I feel like it's something to do with disk activity. It doesn't seem to matter what's being rendered on screen at the time, it's seeing something for the first time that game session which makes the game choke up as art assets are loaded from disk. Running from my NVMe SSD feels like I'm on a laptop hard disk from 2005.

Switching between DXVK and vkd3d-proton doesn't seem to make any difference, and I couldn't see anything interesting in the logs. I might try running with +trace to try and figure out what Wine is getting stuck on.

**Comment by SveSop** [comment]
The first bit of "flying around" actually generates 3 "soft crashes" for WoW. (/_ptr_/Errors folder).
`ERROR #135 (0x85110087) Non-fatal assertion failure!`

This somehow happens when i fly and instead of stutter "a bit", just freeze the picture for a few seconds. After these 3 crashes (does not happen if i log in and just stand without much movement) it does not seem to happen again.

Just as a sidenote of sorts - I have a windows 10 box with my old GTX970 card in it (Old mainboard with DDR2 and AMD Phenom processor), and no matter what nVidia driver i pop there, all hairs and random other character textures are just black. I have tried most drivers from 442.50 (that someone mentioned a year ago fixed some texture flickering on live) to latest WHQL and latest Vulkan beta, without ANY change.

I have search and talked to other ppl online, but it does not seem as there is a wide-spread problem, nor did my kid experience anything like that when he tried it on his RTX2080Ti. I have tried DX12, DX11 and DX11 w/DXVK (And yeah, it works), but the "black texture/hair" issue is the same. Weird.

PS. There is stuttering there aswell, but i cant say the hardware is "up-to-par", so it would be of no surprise, even if it runs from an SSD. And the 3 soft-crashes also happen there. 
Common denominator: PTR Client

**Comment by SveSop** [comment]
> Switching between DXVK and vkd3d-proton doesn't seem to make any difference, and I couldn't see anything interesting in the logs. I might try running with +trace to try and figure out what Wine is getting stuck on.

Yeah, basically what i have been trying aswell, but there is no apparent problem that sticks out. Logging with +trace does generate a lot of useless information tho, and i am in no way tech-savvy enough to figure out what could be happening.

It does seem as whenever the game loads something (hdd led blinking) there is a stutter. It loads more in cities obviously, and thus more stuttering. Tried to ride "out to sea", or enter a more or less empty instance like darkshore, and being by myself does not generate a lot of loading once i am in, so the stuttering is a lot less.

There are also one thing that is removed from recent staging and that is `STAGING_SHARED_MEMORY` Still listed here: [https://github.com/wine-compholio/wine-staging/wiki/Environment-Variables](https://github.com/wine-compholio/wine-staging/wiki/Environment-Variables) but does not exist anymore it seems.

[https://github.com/wine-staging/wine-staging/blob/master/patches/server-Shared_Memory/definition#L9](https://github.com/wine-staging/wine-staging/blob/master/patches/server-Shared_Memory/definition#L9)

Ill do some comparisons between ptr/live running from the same drive just to rule out anything there when using staging-5.17.

**Comment by SveSop** [comment]
I did a comparison of sorts.
wine-staging-5.17 with a couple of added patches (d3d12 and a few minor ones).
"Plain" 64-bit compile with just : `configure --enable-win64 --disable-tests --prefix=/xxxx` 
`WINEDEBUG="warn-all,fixme-all,+seh"`
For retail version from the _retail_ folder:
`wine64 "./Wow.exe" "-d3d12" &>debug.log`
For ptr version from the _ptr_ folder:
`wine64 "./WowT.exe" "-d3d12" &>debug.log`

Just starting up to where i type in my password++, the ptr version uses like a couple of minutes, and generates a 4.9GB debug log, vs the retail version uses <10 seconds and generates 25MB log.

Kinda hard to browse that 4.9GB file in a useful manner, but it kinda seems clear that a lot more exceptions are being made.. If that is due to some "ptr" breakpoints for logging or whatever, i have no clue...
Anyone know what i should look for in the +seh log?

I think there is some exception handling going wrong, which kinda indicates why it would fail when you compile with `--without-mingw` as there has been quite a few fixes to exception handling in the PE version of ntdll.
[https://github.com/wine-mirror/wine/commit/c76dc32feffaeed260bf73499e43012b69bee1b4#diff-46ea01b368df413397abde61e661e262](https://github.com/wine-mirror/wine/commit/c76dc32feffaeed260bf73499e43012b69bee1b4#diff-46ea01b368df413397abde61e661e262)
[https://bugs.winehq.org/show_bug.cgi?id=49698](https://bugs.winehq.org/show_bug.cgi?id=49698)

Kind of the same problem, only in reverse - ie. the bug linked above works when you compile using `--without-mingw` but not with ntdll as PE lib, vs. this WoW problem is the other way around.

So, imo there is something going on with the exception handling that really makes things crawl to a halt. If this will go away once WoW is released, i dont know.... But the problem is definitely not comparable under windows when it comes to performance.

**Comment by SveSop** [comment]
Reverting the following 2 patches:
[https://github.com/wine-staging/wine-staging/blob/master/patches/ntdll-Syscall_Emulation/0001-ntdll-Support-x86_64-syscall-emulation.patch](https://github.com/wine-staging/wine-staging/blob/master/patches/ntdll-Syscall_Emulation/0001-ntdll-Support-x86_64-syscall-emulation.patch)
[https://github.com/wine-staging/wine-staging/blob/master/patches/winebuild-pe_syscall_thunks/0002-winebuild-Call-__wine_syscall_dispatcher-through-the.patch](https://github.com/wine-staging/wine-staging/blob/master/patches/winebuild-pe_syscall_thunks/0002-winebuild-Call-__wine_syscall_dispatcher-through-the.patch)

Caused the _retail_ version of WoW to crash with:
`0024:err:virtual:virtual_setup_exception stack overflow 2032 bytes in thread 0024 addr 0x1400d3ec4 stack 0x120810 (0x120000-0x121000-0x220000)`
Although i had to kill it, it did not generate any more exceptions.

The _ptr_ version also crashing with the same stack overflow but it just kept growing the log > 10GB (where i killed WowT.exe)

**Comment by kenhubcom** [comment]
So it's pretty much confirmed that this is a wine-issue, not related to dxvk/vkd3d/tkg-patches.
I think you should open a bug report on the wine-staging bug tracker with your findings.

**Comment by Thaodan** [comment]
Also try with the plain version of wine to compare.

**Comment by SveSop** [comment]
> Also try with the plain version of wine to compare.

If by "plain wine" you mean "wine-devel", it does not works at all, but if you mean "wine-staging" as provided by WineHQ, the issue is the same. All logs/tests should ONLY be performed by "official" WineHQ provided binaries without custom patches and compiles - And for the case of WoW, it needs to be > wine-staging-5.12 to even be able to log in to PTR servers.

@kenhubcom 
I have been thinking about reporting this as a bug, but even tho it is a "wine issue", it remains to be seen if it is due to WoW utilizing huge amounts of debugging/breakpoints/whatnot on the BETA (PTR) version. I have a slightly bad experiences with reporting bugs with beta windows software.

1. Posting a 5GB+ +seh log file is kinda out of the question i guess (and it will grow to 5GB by the time you are able to enter your login credentials).
2. What logs would be useful for the wine devs? It does not crash as it is now - performance is usually not a huge concern for the devs unless you/we can pinpoint what function is the problem.
3. Are debug versions of windows apps supposed to work "out of the box" on wine? Are there other examples of beta/debug apps (free and lightweight) that could be used to provide a proof of concept for the devs to investigate?

Imo, it is not enough to just make a bugreport with the text "World of Warcraft PTR is slow", cos that might not get us anywhere.

**Comment by SveSop** [comment]
Right. I found out the only thing you need to actually play/login to WoW is plain wine-devel-5.17 (probably earlier aswell, but have not tested) + [https://github.com/wine-staging/wine-staging/blob/master/patches/winebuild-pe_syscall_thunks/0002-winebuild-Call-__wine_syscall_dispatcher-through-the.patch](https://github.com/wine-staging/wine-staging/blob/master/patches/winebuild-pe_syscall_thunks/0002-winebuild-Call-__wine_syscall_dispatcher-through-the.patch)

Without this patch, WoW (both retail and PTR) will crash.

Wine needs to be built --with-mingw flag (the default if not specified), or else it crash.

Assuming you have a fully patched WoW client, you can start WoW with just 64-bit wine (to shorten any testing), but you need to start it using wine64 ofc. Like this:
```
cd /wherever/WoW/folder/_ptr_/"
/wine-installed/folder/bin/wine64 "./WowT.exe" "-d3d12"
```
replace -d3d12 with -d3d11 if you are using DXVK, or -d3d11legacy if running wined3d. 

Thoughts:
- I think there is extensive debugging "enabled" on the WoW PTR client, and this does not work very well with wine
- It is not a "staging bug" in itself, even tho this patch is in staging and not yet upstreamed.
- 2 other patches from the "winebuild-PE syscall" patchset have been upstreamed.

Wine "broke" for running WoW around 5.11/12, just after the esync patches was disabled due to extensive ntdll built as PE lib. This "winebuild-PE syscall" patchset was added around 5.13.
Something has changed with WoW PTR since it is not possible to run on wine-5.7 that runs _retail_just fine.

So for SOME weird coincidence PTR does not run on anything older than when esync patches was disabled and WineHQ started converting ntdll to PE lib. (There might be some overlap here, so you could probably run PTR with 5.11 with some patches.. i dunno, and have no desire to test all the combinations of patch(sets) to figure that out).

But atleast being able to run WoW with just 1 minor patch would make it easier to post a bug on bugzilla i guess!

**Comment by SveSop** [comment]
Just a quick idea why PTR/Shadowlands crashes vs. _retail_

I see that M$ flightsim has a few crashes regarding "mfplat" and gamepad support and whatnot. [https://bugs.winehq.org/show_bug.cgi?id=49740](https://bugs.winehq.org/show_bug.cgi?id=49740) . Although not easily comparable, but what i DO believe is new to shadowlands is the support of various gamepads...
[https://www.wowhead.com/news=313637/in-game-preview-of-gamepad-support-for-shadowlands](https://www.wowhead.com/news=313637/in-game-preview-of-gamepad-support-for-shadowlands)

Could this somehow be something that could cause those crashes with PTR when running from most wine < 5.13? And not being implementet the exact same way that the patches adressing this for M$ flightsim actually is something that could cause these weird slowdowns/stutters atm?

**Comment by gcaliber** [comment]
It will be interesting to see if this is this just a problem with the PTR build or will it carry over at launch/pre-patch.

**Comment by SveSop** [comment]
> It will be interesting to see if this is this just a problem with the PTR build or will it carry over at launch/pre-patch.

Yeah.

I'm at a total loss here. I dont have the knowledge or skills to really do anything useful other than testing, but there is something "changed" with PTR.

I cant get PTR to work on anything < wine-staging-5.13 due to [https://github.com/wine-staging/wine-staging/blob/2ecd3b8b8e63a1210b208968fe5f19512666fb9a/patches/winebuild-Fake_Dlls/definition#L10-L17](https://github.com/wine-staging/wine-staging/blob/2ecd3b8b8e63a1210b208968fe5f19512666fb9a/patches/winebuild-Fake_Dlls/definition#L10-L17)

WHY this is the case, since _retail_ works fine with "anything" even somewhat old 4.16 or whatever, i do not know. _ptr_ does something "new", and that requires ntdll to be a PE lib (it seems), since  5.13 --> 5.17 built using --without-mingw all fail to run.

If the performance would be better with esync/fsync is unknown, but i somehow lean towards this being in the "minor change" - ie. 3-5% or thereabouts when it comes to performance, and not "stutter-shit-out-of-hell" like it is currently, so even with esync/fsync fully rebased, i hightly doubt this issue would be solved, since running _retail_ with wine-staging-5.17 is not THAT huge a difference. (Or wine-5.17 with the winebuild-PE_syscall_thunks patch for that matter).

Testing various patches/reverts+++ on multiple wine versions, i am at a loss.
Even with staging-5.13 its a "gamble", as there are a couple of bugreports about agent.exe and battle.net
[https://bugs.winehq.org/show_bug.cgi?id=45349](https://bugs.winehq.org/show_bug.cgi?id=45349)
[https://bugs.winehq.org/show_bug.cgi?id=49590](https://bugs.winehq.org/show_bug.cgi?id=49590)

I think we kinda need to wait and see. This has taken too much (useless and wasted) time for me to investigate.

**Comment by SveSop** [comment]
It seems as there was a new build today of the WoW client, and it is now listed as "release"..
`Version 9.0.1 (35989) (Release x64)`
This also seems a LOT smoother, tho still requiring wine built --with-mingw (PE ntdll and such).

Feel free to give some feedback, cos if it indeed is not just a random fluke, the "release" version might have disabled loads of error logging or something of that nature perhaps? (Actually less logfiles in the /Logs folder aswell)

**Comment by Thaodan** [comment]
It could be also the case that the beta client has some tracing on that is faster on Windows or only gets enabled on condition that doesn't work on wine.

**Comment by kenhubcom** [comment]
Yes, current PTR is completely smooth, just like the live version. It really seems to be some logging/tracing stuff they do in the beta versions that causes the stutters.

**Comment by zurohki** [comment]
The release version which was up on the PTR was completely smooth.

It has since been discovered that that client version contains a security vulnerability which involved addons being able to run unsecure code in secure mode, so PTR has been reverted to a "Test" version which again runs like crap.

Confirmation that it's the debugging stuff causing performance problems in Wine, I guess.

**Comment by SveSop** [comment]
@zurohki Yeah, that seems to confirm that we should atleast expect a better experience once the game hits the _retail_ servers :)

Do you have a link/changelog to this particular issue on the PTR server that caused this revert?

**Comment by zurohki** [comment]
Nobody's publicly announced details that I can see.

https://old.reddit.com/r/wow/comments/izwxdr/shadowlands_prepatch_ptr_reverted_to_test/g6m7885/

**Comment by cncz42** [comment]
Pre patch in in like 2 days so we better get a fix, wine-staging still doesn't support flipping

**Comment by kenhubcom** [comment]
Current PTR build works flawlessly, and that's the one that's being deployed in 2 days. What's flipping?

**Comment by cncz42** [comment]
> Current PTR build works flawlessly, and that's the one that's being deployed in 2 days. What's flipping?

flipping is some odd nvidia thing that I don't quite fully understand but playing games without it looks super choppy even though displayed framerate is the same. I was saying this since only wine-staging works for ptr and for whatever reason flipping is unsupported on it

**Comment by ninelore** [comment]
> I'll simply have to go deeper, which will be very annoying smile It'll be required for some CoD games as well so heh.. ActiBliz extracting all the fun out of life as usual.

where did that went btw?

**Comment by zurohki** [comment]
Flipping is a way of getting new frames onto the screen which is needed for vsync and such to work.

Flipping seems to be working fine on AMD, I'm getting freesync and everything. Look into your nvidia settings and your compositor's settings, I guess?

**Comment by SveSop** [comment]
So.. is flipping needed for GSync to work?
I cannot get anything other than vsync, or no sync regardless of what the gsync options is saying... And dmesg sometimes spew some lines about "gsync not available" or something or other when i use Wine.

Not sure if this is a dxgi matter (needs some lines to be supported), or a d3d thing (dxvk)... or whatever. Enabling the "visual indicator", indicates that gsync is NOT enabled when i try to use that in wine... Now.. i do use 2 monitors, and i believe gsync cant really be used with 2 monitors?

Found a snippit here (although somewhat old).
[https://forums.developer.nvidia.com/t/gsync-is-not-working/38679](https://forums.developer.nvidia.com/t/gsync-is-not-working/38679)

>  The full-screen requirement includes the game being completely unoccluded, so if your window manager is drawing something on top of the game, even just by one pixel, it will prevent flipping. Full-screen also means that it has to cover the entire X screen, which includes both monitors if you have them both enabled.

WoW does NOT run "full-screen", as the only option is "borderless windowed" or "windowed". It does however go "on top of everything" when using (recent) wine, but i believe that is rather a "hack" than a proper working, cos on my windows box, i can alt+tab windows over the wow window, but i cant do that in wine. I also know my kid got issues in Windows 10 when it comes to gsync + dual monitors.. all kinds of hassle with hz when using 2 monitors of different hz. (Like for me, i use a "standard" 1080p60hz monitor, + my 1440p165hz "main" monitor).

I do believe wine-staging disables compositor by default these days (when running a fullscreen app), and i can see there is happening some magic when i run "real" fullscreen apps... cos then all other windows will be moved to my second monitor + the screens will "flash/flicker" a couple of times before showing the fullscreen app on my "main" monitor. This does NOT happen with WoW tho, which leads me to believe that WoW actually is NOT a proper "fullscreen" app.

Maybe this also breaks "flipping" for that particular game? Does flipping work with other well known "to-be-fullscreen" apps? Eg. Running Unigine Valley in fullscreen does indeed seem to BE fullscreen.

**Comment by ninelore** [comment]
WoW doest got a real Fullscreen anymore since BfA prepatch @SveSop 
only Borderless window

**Comment by SveSop** [comment]
Without bothering to test older wine versions (again), i can tell you that (aside from obvious game bugs) wine-staging-5.19 works just fine with shadowlands pre-patch.

@jporterf  Close the issue as solved?

**Comment by ninelore** [comment]
Could be a me Problem, but im experiencing a input lag of apporx. .5sec with wine-staging-5.19

**Comment by SveSop** [comment]
> Could be a me Problem, but im experiencing a input lag of apporx. .5sec with wine-staging-5.19

I suspect that this COULD be due to servers being somewhat unstable/overloaded at times, and not wine itself. I mean.. there is at times login queues, not to mention the "you need to wait on character select screen for 10+ minutes to log on"... Massive lagg in Boralus+++

But if you have compared this with wine-staging-5.18 (or older) and find it differently, please confirm tho, or else i would write this off as "general serverlagg".

**Comment by ninelore** [comment]
IMO there is no reason to close this issue as long as WoW 9.0.x not working under wine-tkg (this repo)

And i cant write this off as general serverlag when ever windows user i play with doesnt have that issue

**Comment by ninelore** [comment]
The Mouse issue doesnt occur on vanilla staging-5.16

**Comment by SveSop** [comment]
I dont seem to have any particular issues. I do enable 2 options:
1. In winecfg: "Grab mouse in fullscreen window"
2. WoW: SET rawMouseEnable "1"

@ninelore  What do you mean by "WoW 9.0.x not working under wine-tkg"? Does not WoW 9.0.x work with ANY wine-tkg version?

IF you want to troubleshoot wine issues vs. WoW, you can take wine-devel and only apply the patch: [https://github.com/wine-staging/wine-staging/blob/master/patches/winebuild-pe_syscall_thunks/0002-winebuild-Call-__wine_syscall_dispatcher-through-the.patch](https://github.com/wine-staging/wine-staging/blob/master/patches/winebuild-pe_syscall_thunks/0002-winebuild-Call-__wine_syscall_dispatcher-through-the.patch)

Wine must be built `--with-mingw` option tho, as WoW 9.0.x does not seem to work with wine < 5.13, nor does it work if not built with PE support.

**Comment by Tk-Glitch** [comment]
Building against the upcoming staging rebase should allow WoW Shadowlands to work with wine/proton-tkg + esync/fsync.

**Comment by fleggie** [comment]
Anybody got an idea why the finished build won't open up my battle.net Launcher ? I won't get any errors it just won't open up. I used staging `6d726da3ba0130385e352be0c534399d5c7eb29d` and enabled esync and fsync in that cfg. I use lutris and the debug output would be:

[https://pastebin.com/SdniwNxT](url)

Sorry to bother you guys. Ignore this if I am just beeing stupid.

**Comment by Tk-Glitch** [comment]
You need to use current staging (so just leave the version empty `_staging_version=""`). Then it should work.

**Comment by fleggie** [comment]
If I leave that `_staging_verision=""` empty I will always get the `ntdll.dll.so error  c0000135` and the launcher won't open up. Thats why I choosed that other version earlier.

**Comment by Tk-Glitch** [comment]
I'll check it out on my end, but current should be fine. Another user has been playing WoW and OW with no issue on a fresh build.

**Comment by fleggie** [comment]
Using the normal Wine Staging 5.19 works fine but without esync+fsync. I guess I am doing something wrong why I am always getting that ntdll.dll.so error.

**Comment by Tk-Glitch** [comment]
![Screenshot_20201018_154055](https://user-images.githubusercontent.com/741977/96369121-638e5a80-1158-11eb-8152-11ff8e54eb84.png)
I'm unable to reproduce the issue on my machine. Are you building with mingw?

**Comment by fleggie** [comment]
I am building with the building script offered in that folder ? I am sorry to ask but how to I build with thing mingw?

**Comment by Tk-Glitch** [comment]
It's a compiler. On Debian the package seems to be `mingw-w64`.

**Comment by fleggie** [comment]
Oh yes. It's installed. I got that package. Still no idea why I can't launch that compiled wine version. When I try to execute that wine I will always get `wine: failed to load /home/patrik/Dokumente/Kompilieren/wine-tkg-git/wine-tkg-git/non-makepkg-builds/wine-tkg-staging-fsync-git-5.19.r12.gbe9c9681/lib/wine/ntdll.dll.so error c0000135`

**Comment by Tk-Glitch** [comment]
Are you building a debian package (of wine-tkg)? Or are you running it from somewhere else?
Have you tried running `wine-tkg` instead of `wine`?

**Comment by fleggie** [comment]
No I am building wine-tkg git cloned from https://github.com/Frogging-Family/wine-tkg-git.git

I did not check making a .deb in the customization.cfg

After that I open that other distro wiki thread to follow the building instructions on that. I edit the customization.cf to add that parameter to stop when wine64 building is finished to reinstall the i386 packages. After that I continue with building.

After all that I got that non-makepkg-builds/wine-tkg-staging-fsync-git-5.19.r12.gbe9c9681/bin/ directory with wine in it. With this wine I am trying to execute my Blizzard launcher. Am I missing something ?

**Comment by Tk-Glitch** [comment]
It's weird indeed, but I know some distros can lead to weird path issues with wine when it's not installed system-wide. Maybe enabling debian package in your .cfg would be enough of a fix. Of course the package would replace your distro's wine-staging package, but if it breaks you can just reinstall the distro package to replace your -tkg package.

It's been a while since my last Debian testing.. I'll check in Debian's repo if there's a specific change needed for Debian not to break. It might also be a regression upstream. If someone else on Debian has some input on this I'm all ears.

**Comment by fleggie** [comment]
I tried enabling the debian package parameter. 

`_GENERATE_DEBIAN_PACKAGE="true"`

It just shows an error that .deb package function does not really works.... 

Im trying to build an older version of tkg to check if i get the same error. I installed wine-staging systemwide otherwise WoW wouldn't even run. I can run wow with wine-staging but I want to have esync + fsync support so I tried my luck with tkg.

**Comment by Tk-Glitch** [comment]
That error you get might be fixed by setting `_nomakepkg_prefix_path="/usr"` in your .cfg.

**Comment by fleggie** [comment]
I'll try a different path. My wine is located in /opt/ but I will check really quick.

**Comment by FLGX06** [comment]
> I tried enabling the debian package parameter.
> 
> `_GENERATE_DEBIAN_PACKAGE="true"`
> 
> It just shows an error that .deb package function does not really works....
> `> Generating a Debian package Sorry, /home/patrik/Downloads/wine/wine-tkg-git-5.18.r3.g9acfa3b8/wine-tkg-git/wine-tkg-staging-fsync-vkd3d-git-5.18.r3.g9acfa3b8 as prefix is not supported yet in wine-tkg packaging for Debian on Arch ` If I could solve that maybe I am able to generate a .deb
> 
> I'm trying to build an older version of tkg to check if i get the same error. I installed wine-staging systemwide otherwise WoW wouldn't even run. I can run wow with wine-staging but I want to have esync + fsync support so I tried my luck with tkg.
> 
> Older Versions of tkg like 5.18 won't produce the `ntdll` error. But something else is borked.

That option is for generating debian packages during arch build (on arch), I probably should've made it more clear somehow (PR #82)

**Comment by fleggie** [comment]
Oh okay. I see no wonders why it won't work. Honestly I don't know what else I could do now. 5.18 won't show the error 5.19 wont work because of ntdll.dll and at that point I am quite sure that I should switch to Arch...

**Comment by ninelore** [comment]
@fleggie do you tried mostlyportable-gcc?

If you are willing to switch Distro you should try out Manjaro

**Comment by fleggie** [comment]
@ninelore No, should I try ? I am new to this I have to read me in. Well I am not really wanting to switch distro. Ususally everything runs smooth on my system. But I will give mostlyportable a try I guess. Problems should be solved not avoided.

**Comment by fleggie** [comment]
I can't figure out how to use the new mostly-gcc as default gcc. Everytime I try to set `CC="my/path/to/mostlyportable-gcc/gcc-mostlyportable-9.2.0/bin/gcc" make` he always wants to compile not set the environment variable for gcc.

**Comment by ninelore** [comment]
did u set it in your `advanced-customisation.cfg` or in your externel configuration file? The Variables are `CUSTOM_MINGW_PATH=""` and `CUSTON_GCC_PATH=""`

**Comment by fleggie** [comment]
Oh thank you. I though I have to set it complete in my PATH

**Comment by fleggie** [comment]
Thank you for your help everyone. I build wine-tkg with mostlyportable and the Blizzard Launcher opens up without any problems. I don't know why it works now. Before that I guess I used my Debian gcc and mingw-64 for that. If anyone needs anything concerning my setup feel free to ask. I will gladly post my configurations here.

**Comment by Thaodan** [comment]
Can you talk about your problem in another bug and don't spam this one?!

**Comment by fleggie** [comment]
Ok @Thaodan didn't want to bother people doing their jobs. Though it was fitting that the thread title was referring to World of Warcraft freezing when launched. So did my game when launching with any wine < 5.19. So I posted here and did not open a new thread. Nevertheless I hope you are having a great day.

**Comment by ninelore** [comment]
The OP's Problem was solved with the introduction of the new Esznc/Fsync. It think this can be closed now

**Comment by Tk-Glitch** [comment]
@fleggie That's pretty weird. Debian's GCC at least (not sure about MinGW) has various patches applied on top that may break our usecase here. If mostlyportable worked (I assume you built both GCC and MinGW with it?), which uses basically untouched sources, it seems logical to me to think about Debian's GCC or MinGW toolchains to be the problem. I'm glad it's fixed for you nonetheless.

Since I have been able to verify that the game now works fine on -tkg, let's close.

**Comment by SveSop** [comment]
Since Debian/Ubuntu multilib build system is a pita, it would not surprise me that something goes wrong when the script tries to build 32/64-bit libs there...

I have not tested the latest tkg-5.19, but have had no huge issues building tkg releases "manually" like i always do tho - pulling source with script set to `_NOCOMPILE="true"`, then using lxc for the 32-bit parts of the compile.

**Comment by Thaodan** [comment]
Can you create a new bug? Learn how to use bugtrackers pls

**Comment by Thaodan** [comment]
Is it broken again?

I'm using wine-staging '02be23fa5213c0cb0b377b5120ea256d6b5f1af4' and wine-tkg 'bcf4f949bc9b3c53d517abf767e2361e1d4b1436'.

**Comment by Thaodan** [comment]
Nevermind it was me forgot to change that the pkgname changed.
