### ISSUE TITLE
Patch Application has failed (prepare())

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#107]
Im attaching my prapare.log and my externaĺ customisation file

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5074196/prepare.log)

[wine-tkg.cfg](https://github.com/Frogging-Family/wine-tkg-git/files/5074204/wine-tkg.txt) (changed to .txt)

**Comment by netbospl** [comment]
Same here. Since Wine 5.15 release it has started to happen.

ed8358393413d52096c56e96b44ee73f15053f91 reverted (hotfix)
Auto-merging server/trace.c
Auto-merging server/request.h
Auto-merging server/protocol.def
Auto-merging server/console.c
Auto-merging include/wine/server_protocol.h
CONFLICT (content): Merge conflict in include/wine/server_protocol.h
Auto-merging dlls/kernelbase/console.c
CONFLICT (content): Merge conflict in dlls/kernelbase/console.c

**Comment by netbospl** [comment]
> Im attaching my prapare.log and my externaĺ customisation file
> 
> [prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5074196/prepare.log)
> 
> [wine-tkg.cfg](https://github.com/Frogging-Family/wine-tkg-git/files/5074204/wine-tkg.txt) (changed to .txt)

In customization.cfg set following options

`# plain wine commit or version tag if you want to use a specific wine version. Can use e.g. "64d9f30", "wine-3.16" or "wine-4.0"
# !!! Only affects non-staging builds (you want to edit the staging_version below for staging builds) !!!
# Leave empty to use latest master - https://github.com/wine-mirror/wine/commits/master
_plain_version="wine-5.14"

# staging
_use_staging="true"
# staging commit or version tag if you want to use a specific staging version. Can use e.g. "7cfceb7", "v3.16" or "v4.0"
# Leave empty to use latest master - https://github.com/wine-staging/wine-staging/commits/master
_staging_version="v5.14"`

And it will compile fine

**Comment by Tk-Glitch** [comment]
Should be fixed as of https://github.com/Frogging-Family/wine-tkg-git/commit/b22d1cdad19e5aba27fbff1d43277ab519798339
