### ISSUE TITLE
[proton-tkg] Valve bleeding edge, had to skip d3dx9_36-D3DXOptimizeVertices and d3dx9_36-D3DXStubs

### ISSUE THREAD

**Issue by mikeserv-git** [Frogging-Family/wine-tkg-git#1098]
I found I had to skip these patch sets to build the current "valve bleeding edge" choice.

 -W d3dx9_36-D3DXOptimizeVertices -W d3dx9_36-D3DXStubs

Those touch many d3dx9 .spec files in different places (with patch failure in every one) and I'm not sure it would be a good use of anyone's time to fix them for temporary usage, at this point in limbo.

I think the first one fixes a game, "Timeshift" and not sure exactly what the consequences of the second patchset would be. I presume those are for WineD3D (I don't use that at all, I use DXVK, moreover I can't due to the way I build my Mesa now anyway)

By the way, what toolchain components are we behind on, that is keeping us back with f5e9c76903e4e18e0416e719a6d42d0cb00998aa for bleeding edge's wine base? Something on the host system like mingw being out of date?

**Comment by Tk-Glitch** [comment]
Thanks for reporting! I'll see what I can do.

Bleeding edge's wine base is current, only the proton-specific bridging tooling is locked to f5e9c769 (lsteamclient, vrclient, steam.exe...). The build process for them has changed upstream in a way that breaks our approach, so we'll have to make a new path. However, since the slightly older tooling works nonetheless while using current bleeding edge wine-proton base (as well as wine upstream base), it's not a huge issue at this point in time and low priority.

**Comment by mikeserv-git** [comment]
Ahh, I see, thanks for the explanation. I misunderstood what ValveSoftware/Proton/tree was (thought the wine submodule would be part of the checkout).
