### ISSUE TITLE
Curiosity: valve wine has hardcoded steamuser as the username

### ISSUE THREAD

**Issue by adolfintel** [Frogging-Family/wine-tkg-git#1136]
I noticed that since Proton 9, valve's version of wine ignores the unix username and literally hardcodes "steamuser" in dlls/advapi32/advapi.c

I agree with this change, but do you know why this was done?

**Comment by Tk-Glitch** [comment]
This is nothing new and was already the case since the first Proton release: https://github.com/ValveSoftware/wine/commit/159c20ae3e15731f4011008cb70499ab60f0e3fb
The code was adapted for newer wine versions of course, as you can see for Proton 7 here: https://github.com/ValveSoftware/wine/commit/df134c39cab2e1a32c75d34d7b9348482abe73d1 or 8 here: https://github.com/ValveSoftware/wine/commit/653847dd8d2740ee886648e96a3eb20db6a6cbe7

**Comment by adolfintel** [comment]
Oh, I had no idea it was a tkg patch that reverted this change. Will you update it for Proton 9?

**Comment by Tk-Glitch** [comment]
It's due to https://github.com/Frogging-Family/wine-tkg-git/issues/1132
The de-steamify patchset was removing steam-specific changes to make wine builds based on Valve trees closer to a "normal" wine build. But yes it will be updated for proton 9 trees soon.
