### ISSUE TITLE
Can't build on Arch Linux with vkd3d fork

### ISSUE THREAD

**Issue by D3SOX** [Frogging-Family/wine-tkg-git#116]
I'm trying to build proton-tkg on Arch Linux with the vkd3d-proton fork

What I did:
```
git clone https://github.com/Frogging-Family/wine-tkg-git.git
```
(On commit https://github.com/Frogging-Family/wine-tkg-git/commit/642847e4f500993bb8d64aa88f526aff508c21b8)

Edited `proton-tkg/proton-tkg.cfg` and set `_use_vkd3dlib="fork"`
```
cd wine-tkg-git/proton-tkg
makepkg -si
```

Now I'm stuck with this error:

```
make[1]: Leaving directory '/home/nico/building_stuff/wine-tkg-git/wine-tkg-git/src/proton_dist-64-build/dlls/d3dcompiler_46'
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 -> Compilation time for 64-bit wine: 

real    0m1.130s
user    0m10.089s
sys     0m1.953s

==> ERROR: A failure occurred in build().
    Aborting...
```
Complete makepkg output: [makepkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/5129900/makepkg.log)

I have tried to also set `_use_vkd3dlib="fork"` in combination with `_dxvk_dxgi="true"` or `false` in `wine-tkg-git/customization.cfg` ending up with that same error.

I'm sorry if this is some kind of noob error.

**Comment by Tk-Glitch** [comment]
So there are indeed subtleties about this.

 - The preferred option is to use the default of `_use_vkd3dlib="false"` to build vkd3d-proton standalone (d3d12.dll) instead of using a shared lib. It also allows for better compatibility.

 - If you really want it, to be able to make use of the `_use_vkd3dlib="fork"` option, you need to have the related vkd3d-proton (fork) package installed (https://github.com/Frogging-Family/vkd3d-git). Your error seems to indicate that you have a regular vkd3d package installed, which isn't compatible. If you have the correct package installed, it might be worth a try to set `_fork_disable_meson="true"` in the vkd3d-git's `customization.cfg` then rebuilding. It wasn't needed last time I checked so it could be a recent regression.

Hope it helps :wink:

**Comment by D3SOX** [comment]
Thank you. I didn't know that I had to install the fork on my system (Yes I had regular vkd3d installed).
I'm trying to get Horizon Zero Dawn running. I think I can figure it out now.
Anyway, thanks for your help.

**Comment by Tk-Glitch** [comment]
For HZD and a few other d3d12 games, you'll actually *need* a standalone d3d12.dll build (which you'll get with `_use_vkd3dlib="false"`.
