### ISSUE TITLE
Feature request: install only flag for proton-tkg.sh

### ISSUE THREAD

**Issue by UQuark** [Frogging-Family/wine-tkg-git#1179]
I am waiting for it to recompile for a third time in a row. First two were related to missing dependencies, and the third one is just me guessing wrong on question "Do you want to delete superfluous builds from steam compatdata?". I answered "Y" and it immediately crashed with a message that there must be two or more existing Proton installations to clean it up. Very nice. A fatal error, worth exiting the script entirely.
There's no straightforward way to install an already built distribution. Build process is only partially cached.

**Comment by mikeserv-git** [comment]
I know this is a closed report, but it's worth mentioning that there's a good reason for that.

If you start Steam, and your already configured compatibility tool is gone, it can break all your configured games, reverting them back to the default Proton tool or in the case of both a Windows and Linux version, may delete and start downloading the files to convert it. It's not going to upgrade to the next one like Valve's Protons will, they control their own manifests like that.

It's also worth noting that there are two convenient variables in proton-tkg.cfg that you can use to mitigate this undesired behaviour:

```
# Set to true if you want to skip the uninstaller at the end of proton-tkg building
_skip_uninstaller="true"

# Set to true if you do not want your build to be automatically moved to your compatibilitytools.d dir
_no_autoinstall="true"
```

I set both of those to true, because I'd rather just manually copy the directory to compatibilitytools.d. I use the same tool names (both internal and friendly names) for all (in compatibilitytool.vdf template), so Steam won't ever screw up my game configurations. I only use my own tool, never theirs and I wouldn't want to accidentally drop two in there :-)
