### ISSUE TITLE
undefined reference to dlopen and dlsym

### ISSUE THREAD

**Issue by Lepidos** [Frogging-Family/wine-tkg-git#122]
Compilation failed on _function build_lsteamclient_ on my debian bullseye machine 

https://github.com/Frogging-Family/wine-tkg-git/blob/c2052b67592f5d6e27b5646b8fd5c971898a315d/proton-tkg/proton-tkg.sh#L145

replacing with:
_ _cxx_addon+="-Wl,--no-as-needed -ldl"_

solves the issue.

**Comment by reticulatedpines** [comment]
I had this too.  I believe the reason for this is because "-ldl" is ahead of the .o files in the command line.  Some compilers regard the order as significant (notably GCC).  Moving "-ldl" after all the .o files fixed it for me.

https://stackoverflow.com/questions/35324324/about-the-ldl-flag-while-compiling-and-linking-c-files

**Comment by Tk-Glitch** [comment]
This seems to be unique to Debian-based and using `-Wl,--no-as-needed -ldl` breaks on all other distros :frog:

**Comment by Tk-Glitch** [comment]
Hopefully this will do
