### ISSUE TITLE
[proton-tkg-staging.patch] Build failure

### ISSUE THREAD

**Issue by meflove** [Frogging-Family/wine-tkg-git#1223]
Hi, I had the following crash on Arch with the following config options:
```
_use_ntsync="true"
_launch_with_dedicated_gpu="false"
_FS_bypass_compositor="true"
_proton_fs_hack="true"
_msvcrt_nativebuiltin="true"
_win10_default="false"
_protonify="true"
_wayland_driver="true"
```
Flavour choice:
```
When you are ready, press enter to continue.
  -> No _LOCAL_PRESET set in .cfg. Please select your desired base (or hit enter for default) :
==> WARNING: ! "mainline" and "staging" options will make clean & untouched wine and wine-staging builds, ignoring your .cfg settings !
==> WARNING: ! "valve" profiles will use Valve proton wine trees instead of upstream, ignoring many incompatible .cfg settings !
==> WARNING: ! "default-tkg" profile will use the main customization.cfg and wine-tkg-profiles/advanced-customization.cfg files !
  ->   0 - default-tkg
  ->   1 - mainline
  ->   2 - protonified
  ->   3 - staging
  ->   4 - valve-exp-bleeding
  ->   5 - valve
  ->   6 - other & legacy
  choice [0-6]: 0
```
Crash log:
```
  -> Applying proton-tkg-staging.patch
==> ERROR: Patch application has failed. The error was logged to /home/user/build/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
```
prepare.log:
[prepare.log](https://github.com/user-attachments/files/16321358/prepare.log)

**Comment by Xoxotynn** [comment]
Don't know if this a bug or not

but the problem is with this patch(as comment said it's for Forza Horizon 4):
[proton-tkg-staging.patch](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/proton-tkg-staging.patch#L2773)
start line: 2770
end line: 2844

if you remove these lines and set next value to false in [customization.conf](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/customization.cfg):
`_proton_eac_support="false"`
it'll build successfully

but I'm not sure that these changes won't break anything, so do it at your own risk
