### ISSUE TITLE
Proton: ERROR: A failure occurred in build

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#1224]
Arch Linux;
f2039da837253205ee6727519570d030ee4a9eb8
[last_build_config.log](https://github.com/user-attachments/files/16331480/last_build_config.log)
[prepare.log](https://github.com/user-attachments/files/16331483/prepare.log)
![Screenshot from 2024-07-22 15-17-27](https://github.com/user-attachments/assets/828ac7ea-fea7-4876-bc25-e73ee2e1e839)

**Comment by Tk-Glitch** [comment]
Your wine build failed somehow so you're missing the shared dir.

Weirdly you have the proton patchset failing hunk, as if your tree was missing https://github.com/Frogging-Family/wine-tkg-git/commit/0ac331d25e6dd95104a61687fb5abd5847a73357
Other than that, ntsync is broken currently due to external factors and you should try without it.

**Comment by Kerrung** [comment]
Fixed now, tnx!
