### ISSUE TITLE
explorer.exe and wineserver processes sudden high CPU usage

### ISSUE THREAD

**Issue by irvng-wav** [Frogging-Family/wine-tkg-git#1239]
Hello! First of all thank you for your work. I'm using `wine-tkg-staging-fsync-git-9.15.r0.g92374493-327` (fsync enabled on .bash_profile) for running windows music production plugins on Linux because [that's what the creator of  yabridge recommends](https://github.com/robbert-vdh/yabridge?tab=readme-ov-file#performance-tuning). At first I was getting awesome performance but I ran into a strange behavior.

Every time I move through my project timeline I get really high cpu usage on the processes mentioned in the title: `explorer.exe` and `wineserver`, here are two videos:

The first one is with the program called REAPER, it's where the problem is most present (please also note the cpu monitor on the top right of my screen):

https://github.com/user-attachments/assets/64dc3dcc-da7f-4481-812c-4432091ae710

This second one is with Bitwig Studio, still the same behavior although the CPU stress is less than REAPER:

https://github.com/user-attachments/assets/2079de83-5225-47fb-ba9c-108651a3c4c3

With vanilla wine-staging this issue doesn't happen.

This is my customization file, I disabled most of the game patches because I don't play videogames on this machine, I just use it for music production:
[customization.txt](https://github.com/user-attachments/files/16573016/customization.txt)

Besides that I'm really enjoying wine-tkg. Hope you can help me.

I'm running Arch Linux with `Linux 6.10.2-arch1-1` kernel and GNOME 46 Wayland session.
 
Thanks in advance!

Edit: I built and installed wine-tkg again but this time leaving customization.cfg to it's default state. The problem persists.

Edit 2: This happens only on GNOME's Wayland session. Xorg doesn't have this problem. I just tested it.

**Comment by konomikitten** [comment]
I have a similar problem when play Guild Wars and Guild Wars 2. It seems to happen when the game is in the background rather than the foreground. I've observed the behaviour with the following builds:

```
wine-tkg-staging-fsync-git-9.13.r6.gfe62b910
wine-tkg-staging-fsync-git-9.14.r4.gc23ee1bf
wine-tkg-staging-fsync-git-9.15.r0.g92374493
```

Here's a screenshot of `explorer.exe` and `wineserver` using cpu for no reason I can discern:

![image](https://github.com/user-attachments/assets/47e440f4-ea97-4315-80eb-d1d06ed503da)

This doesn't happen on `wine-ge-custom` specifically `lutris-GE-Proton8-26-x86_64`. This has only been something I've observed with `wine-tkg-git`

**Comment by Tk-Glitch** [comment]
Wine-ge is based on Valve's proton tree, which you *could* select to make wine-tkg builds too instead of upsteam based. That's what I tend to use these days myself as my system-wide wine.
Wine upstream is prone to regressions and behavior changes (notably we had a recent breakage of winewayland, which might be linked to your issue @irvng-wav ).
Regarding the explorer.exe and wineserver high loads with GW/GW2 it sounds like a different issue. I assume fsync was enabled?

**Comment by irvng-wav** [comment]
> Wine-ge is based on Valve's proton tree, which you _could_ select to make wine-tkg builds too instead of upsteam based. That's what I tend to use these days myself as my system-wide wine.

![imagen](https://github.com/user-attachments/assets/2f17c2cf-2788-404e-98fd-9b2b3ce7f4cd)

Is "protonified" Wine-ge?

**Comment by Tk-Glitch** [comment]
`valve-exp-bleeding` will give you a similar build to wine-ge. Protonified is patching upstream with a selection of proton patches. We should add some details about those presets.

**Comment by irvng-wav** [comment]
> `valve-exp-bleeding` will give you a similar build to wine-ge. Protonified is patching upstream with a selection of proton patches. We should add some details about those presets.
Thank you, I'm building `valve-exp-bleeding` right now. I forgot to ask if it supports fsync, since that's esential for getting the most out of music production plugins as far as I understand. I will do some testing and report my findings.

**Comment by konomikitten** [comment]
@Tk-Glitch I know this is a bit "me me me" but I'd really really appreciate it if we could have more CI's or builds released, I come here cause I really don't want to build wine all the time. And I feel like the current CI build isn't working out well for games.

**Comment by irvng-wav** [comment]
@Tk-Glitch `valve-exp-bleeding` worked without issues with fsync enabled, but then I also tried `default-tkg` set to wine staging version 9.10 and that also worked flawlessly. I'm sticking with `default-tkg`, thank you for your help!
