### ISSUE TITLE
Compile latest Wine with srvcli-dll and netutils-dll patches. No luck.

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/wine-tkg-git#127]
I'm trying to compile latest Wine with the two patches [here](https://bugs.winehq.org/show_bug.cgi?id=49739) in order to [run Flight Simulator 2020](https://github.com/ValveSoftware/Proton/issues/4134). I'm renaming the patches extension to `.mystagingpatch` and putting them at  `wine-tkg-userpatches` folder.

[customization.cfg
](https://pastebin.com/mhScp4zT)

[Error log](https://pastebin.com/6pJ1Jm8q)

**Comment by Tk-Glitch** [comment]
Your patch isn't targeting staging but mainline, which is why it fails to apply. The correct extension to use would have been `.mypatch` in this case.
Those patches were staged a few days back, so unless you have disabled staging, wine/proton-tkg will have them already (which will prevent patching them in again, too).

https://github.com/wine-staging/wine-staging/commit/298af8f9fe64c2f52f050a8979b652d4fc831b3d
https://github.com/wine-staging/wine-staging/commit/424cc0395cebb137a6c57319e4f25c0f52a71e18

So just build current (with staging enabled) and you're good to go. Also those two aren't enough for the game to run. https://github.com/wine-staging/wine-staging/commit/db87b45e49a0fa887bc24e232b51cc1a8cb996ec is also needed (and was also staged, very recently). I don't know if the game is playable just yet though.

**Comment by SveSop** [comment]
> I don't know if the game is playable just yet though.

[https://bugs.winehq.org/show_bug.cgi?id=49740](https://bugs.winehq.org/show_bug.cgi?id=49740)

> And here's a stub implementation of the missing windows.media.speech.dll. It could be better implemented using the widl patches I'm trying to upstream, but this one should be standalone.
> 
> This should allow to play the game, although online mode doesn't work.

**Comment by Tk-Glitch** [comment]
Good! Thanks. So it should work OOTB minus online mode by building current.
