### ISSUE TITLE
Missing headers for wined3d-interop.h during x32 proton build, path looks wrong

### ISSUE THREAD

**Issue by JooJooBee666** [Frogging-Family/wine-tkg-git#149]
Kubuntu 20.04, 64bit completes.  normal wine-tkg completes as well.

`wineg++ -m32  -c -Wno-attributes -std=c++0x -O2 -g  -I/build/source/PKGBUILDS/wine-tkg-git/proton-tkg/proton_dist_tmp/include/wine/windows/ -I/build/source/PKGBUILDS/wine-tkg-git/proton-tkg/proton_dist_tmp/include/ -I/build/source/PKGBUILDS/wine-tkg-git/proton-tkg/proton_dist_tmp/include/wine/-Wl,--no-as-needed -I/build/source/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/build/vrclient.win32/vrclient/ -I/build/source/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/build/vrclient.win32/ -I.   -o struct_converters_1916.o struct_converters_1916.cpp`
`vrclient_main.c:22:10: fatal error: wined3d-interop.h: No such file or directory`
`   22 | #include "wined3d-interop.h"`
`        |          ^~~~~~~~~~~~~~~~~~~`

However, the path of `/build/source/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/` does not exists at all so I surmise a variable in the build script is incorrect....I just don't know which one or where.  Any help would be greatly appreciated.  I would LOVE to finally get a build completed here someday. :rofl:

**Comment by Tk-Glitch** [comment]
That path gets nuked on exit, and is just a symlink to `wine-tkg-git/proton-tkg/external-ressources/Proton/`. This is past wine compilation. This is building steam's vrclient libs.

That `wined3d-interop.h` file doesn't exist by default in wine, and requires the application of the proton-vr patchset. Could you please attach your `wine-tkg-git/wine-tkg-git/prepare.log` and `wine-tkg-git/wine-tkg-git/last_build_config.log` files?

Until the actual issue you're facing is understood, setting `_steamvr_support="false"` would be a workaround.

**Comment by JooJooBee666** [comment]
I forgot to mention I already DO have `_steamvr_support="false"`

Anyhow, I've attached all the files and a copy of my current config as well. :+1: 


[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5255234/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/5255236/last_build_config.log)
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/5255241/proton-tkg.cfg.zip)

**Comment by Tk-Glitch** [comment]
Ok so I'm noticing you're not using an external config file and directly editing the default "simple" one directly. You need to know that the options not present in `wine-tkg-git/proton-tkg/proton-tkg.cfg` will be covered by `wine-tkg-git/proton-tkg/proton-tkg-profiles/advanced-customization.cfg`, and adding any of the "advanced" options to `wine-tkg-git/proton-tkg/proton-tkg.cfg` manually will see their values overridden.

Your `_steamvr_support="false"` addition to `wine-tkg-git/proton-tkg/proton-tkg.cfg` gets overridden as a result and it's still enabled.

The best way, in my opinion, is to use the `TkgThingy` script in the root of the PKGBUILDS repo, and to create external config files with it for the projects you're interested in (proton-tkg in this case). Alternatively, you can manually copy `wine-tkg-git/proton-tkg/proton-tkg-profiles/sample-external-config.cfg` to `~/.config/frogminer/proton-tkg.cfg` for the same result. That way you'll have a centralized configuration that will survive git pulls, and will be able to override default settings.

Regarding the 32-bit issue, if the 32-bit side of Wine (proton-patched) didn't build, you won't be able to build required libs later on. So if I understood correctly and something breaks earlier than your log above regarding the vrclient lib, that'll be the actual thing to fix (which is more than likely dependency-related).
I haven't tested Ubuntu since 19.04, but some of my notes here might be of help: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/non-makepkg-build.sh#L15

**Comment by JooJooBee666** [comment]
Ok, I wasn't aware of that.  I setup a config under the ~/.config/frogminer/ as suggested and was finally able to get a build today after fixing another linker issue with gcc and libc (a problem I caused myself AFTER filing this issue) and changing all the gcc and g++ mingw from win32 to posix for dxvk.

FINALLY. :trophy: 

However, this still doesn't explain the issue with SteamVR.  I still have the same error when`_steamvr_support="true"` is set but the build actually completes?

Logs attached for review.

[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/5264870/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5264871/prepare.log)

**Comment by Tk-Glitch** [comment]
A dependency on the 32-bit side might be missing for steamvr support I suppose.

Could you please attach the output of running `./non-makepkg-build.sh --deps64` and `./non-makepkg-build.sh --deps32` (in `wine-tkg-git/wine-tkg-git/`)? That should list all missing optional dependencies, if any. By the way, a few are pretty much useless for most people, let alone for gaming, so no need to attempt having them all installed/detected.

**Comment by JooJooBee666** [comment]
Sure, here ya go.  I can't find the right package and no Google searches have yielded anything definitive on the libhal problem.  Also, the libusb-1.0 I can't figure out either.  I have libusb-1.0-0:i386 and libusb-1.0-0-dev installed but Wine just doesn't care :disappointed: 

[deps64.log](https://github.com/Frogging-Family/wine-tkg-git/files/5283896/deps64.log)
[deps32.log](https://github.com/Frogging-Family/wine-tkg-git/files/5283911/deps32.log)

**Comment by Tk-Glitch** [comment]
You can skip these honestly. I'm sorry I didn't notice earlier about that `WINEMAKERFLAGS+="-Wl,--no-as-needed -ldl"` change you did. The issue was closed by the one who opened it after I pushed https://github.com/Frogging-Family/wine-tkg-git/commit/fc8a71ee44d4db0ccc880a0441ec388d03ba9df4 . I'm not sure if it's actually fixed since there was no actual feedback after the change, but I'd try without altering the default flags. That `wined3d-interop.h` file can't really be missing if the proton-vr patchset is applied (as seen in your logs), and wine compiled correctly (seems to be fine as well).

**Comment by Tk-Glitch** [comment]
Supposedly fixed. Closing.
