### ISSUE TITLE
[Question] About WINE_MEM_ALLOC_MOD

### ISSUE THREAD

**Issue by iWeaker4you** [Frogging-Family/wine-tkg-git#20]
What would be the equivalent of "wine_mem_alloc mod" (Proton GE ) in Wine TKG?

In ProtonDB they have reported that it helps for the problem in FFXV that crashes when playing for a long time since it is accumulating the consumption in RAM.
It is a problem that I have presented several times.

**Comment by Tk-Glitch** [comment]
It's the mk11 patch. On recent versions of it just enabling it is enough, no need for an env var.

**Comment by Tk-Glitch** [comment]
Sidenote - I haven't had an issue with FFXV without that patch applied. Could be due to AMD GPU or 32GB RAM though.

**Comment by iWeaker4you** [comment]
So I don't know what happens, after 3 or 4 hours of play, it just crashes, yesterday I applied the MK11 patch, and it crashes, maybe it's Drivers problems, because with games like FFX / X-2 there is a crash what happens during fights but I think this is Wine's problem at the moment.

I have i7 3770k, 16GB Ram and GTX 1080.

**Comment by Tk-Glitch** [comment]
FFX/X-2 have a different issue that's due to them being 32-bit (and also very poorly made). LAA helps a bit but they'll often still end up out of address space, even on Windows. With DXVK using more memory than native, the issue strikes harder for us - and even more so with d3d9.

In the case of FFXV, it's a 64-bit d3d11 game so address space shouldn't ever be an issue. Recent Nvidia drivers seem to have more stability issues so yeah, it could be related.

**Comment by massatt212** [comment]
i cant get MK11 running on 5.6
can u give me a lil help

**Comment by Tk-Glitch** [comment]
I don't have the game myself nor any experience regarding running it with Wine, so I can't really help. Anyway that's off topic, I'll close this.
