### ISSUE TITLE
Sea Of Thieves (1172620): failed to setup a crew session

### ISSUE THREAD

**Issue by shumvgolove** [Frogging-Family/wine-tkg-git#214]
- System: Arch Linux
- Linux 5.9.8-0
- GPU: AMD RX590
- Mesa 20.2.2
- Logs: [steam-1172620.log](https://github.com/Frogging-Family/wine-tkg-git/files/5541631/steam-1172620.log)

Unlike https://github.com/ValveSoftware/Proton/issues/3931, `proton-tkg` can successfully launch the game and proceed to the menu, but can not connect to the server, so things like invitations by crew mates or just simply starting a mission doesn't work. Similar issue has been described by this person: https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-718221380. This workaround doesn't work: https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-640119255.

![2020-11-15-032011_grim](https://user-images.githubusercontent.com/37271604/99159892-28992b80-26f2-11eb-81f9-31044e4d48f8.png)

**Comment by shumvgolove** [comment]
Just rebuilded and installed `proton-tkg-git 5.21.r10.g7734f7a8-1 (Fri Nov 20 17:09:53 2020)` and updated Sea of Thieves to latest update (November 18). Unfortunately, nothing's changed ¯\_(ツ)_/¯

**Comment by mehgames** [comment]
Wanted to confirm, seeing the same behaviour on `6.0rc3.r0.g9912133b`.

If you get "Corsebeard" errors, the game seems to need to be restarted completely.

After login, always get `Cyanbeard` error (can be ignored). Right before the game launches will get network related error "Longbeard". The strange part is, every few tries the game just loads fine.

The problem is, it will only load 1 out of every 50 attempts when debugging (so not viable to depend on luck).

I will attempt to post more robust debugging logs later. I hope this report helps figure out whats going on here.

**Comment by shumvgolove** [comment]
To fix the issue, one should:
1. Generate `en_GB` locale.
2. Launch `steam` with `LANG=en_GB`

Happy sailing.
