### ISSUE TITLE
Weird behavior with d3d12.dll

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/wine-tkg-git#228]
Hello @Tk-Glitch,

I have just noticed a strange behavior. When I compile Wine TkG with `_use_vkd3dlib="false"` and **without** the vkd3d package installed, we have a Wine construction that doesn't generate `d3d12.dll` when creating the prefix. As a result, the vkd3d-proton script cannot replace the corresponding dlls (I already reported the problem to Josh).

However, when we compile Wine TkG always with `_use_vkd3dlib="false"` and with the vkd3d package installed, we will have a Wine build that generates d3d12.dll when creating a prefix.

I must admit I don't see how we can solve the problem in an ergonomic way for the user. Would it be up to Josh to correct this behavior ?

**Comment by Tk-Glitch** [comment]
When using `_use_vkd3dlib="false"`, we shouldn't have a d3d12.dll file (independently of the vkd3d lib presence), due to:
```
	if [ "$_use_vkd3dlib" != "true" ]; then
	  _configure_args+=(--without-vkd3d)
	  echo "Not using vkd3d native library for d3d12 translation (allows using vkd3d-proton)" >> "$_where"/last_build_config.log
	fi
```
Unless, of course, the switch is broken upstream, which wouldn't surprise me much. It's not really important imho.

> As a result, the vkd3d-proton script cannot replace the corresponding dlls (I already reported the problem to Josh).

That's not our problem really. The script shouldn't need d3d12.dll presence and it should be fixed upstream. That being said, installing it is just dropping the dll and setting it as native. For people not using lutris nor proton nor their own automation script for d3d12 games, that's not too involved I think :stuck_out_tongue: .

**Comment by IroAlexis** [comment]
Exactly, I had looked at your `prepare.sh` script to be sure but despite that the vkd3d package installation solves what I explained. I'm doing it now to be sure and while waiting for vkd3d-proton upstream changes.

> Unless, of course, the switch is broken upstream, which wouldn't surprise me much. It's not really important imho
There is a good chance that this is the case.

Anyway, thanks for answer and understood for me :frog:

**Comment by IroAlexis** [comment]
I just noticed that the switch seems to be fixed. Test : When we compile Wine TkG always with _use_vkd3dlib="false" and with the vkd3d package installed, we will have a Wine build that don't generates d3d12.dll when creating a prefix.

I can close the issue ?

**Comment by Tk-Glitch** [comment]
Great news! Sure :smiley:
