### ISSUE TITLE
Compatibility between esync and protonify

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/wine-tkg-git#238]
Hello Frog Master,

I dont' know if we can disable fsync (but enable esync) with the `_protonify` patch. Indeed, I tried this combinaison for bypass the hotfixer (lazy to look at the code :upside_down_face:) and I got this patch application error [prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5687795/prepare.log)
I think more that `_protonify` can't use without fsync but maybe I misstake.

Thanks for all

**Comment by Tk-Glitch** [comment]
The CPU topology override stuff added yesterday (https://github.com/Frogging-Family/wine-tkg-git/commit/535c6bff2305603486a6261e1bbaf8ac1bfde8af) seems to be the culprit. I'll have to split them and add a dependency on fsync. That being said I don't understand parts of your message.

> disable fsync (but enable esync)

Since you're using staging, esync is in by default, even if disabled in config (as it would make many staging patchsets fail), *BUT* - and that's important here - it is not enabled by default and requires `WINEESYNC=1` envvar to get enabled. It's the exact same story for fsync. If you don't pass `WINEFSYNC=1`, fsync won't be enabled. If you're using some third party tool that enables it against your will, you can pass `WINEFSYNC=0` to turn it off.

For proton builds, however, the proton script steam uses to run your games enables both esync and fsync (fsync being used over esync if a compatible kernel is installed). You can enforce fsync to be disabled with `PROTON_NO_FSYNC=1 %command%` as launch parameter for your game in steam, or set it globally in your proton build's `user_settings.py`. No need to disable the patchset altogether (or rebuild) just to disable fsync.

> I tried this combinaison for bypass the hotfixer

The esync/fsync hotfixer is gone since 5.20. There is zero reason to do that. The only thing the hotfixer does currently is reverting bd27af974a21085cd0dc78b37b715bbcc3cfab69 because it breaks a large amount of apps and game launchers (https://bugs.winehq.org/show_bug.cgi?id=49990). And of course, this has nothing to do with esync/fsync.

**Comment by IroAlexis** [comment]
In fact, when I use [this config](https://github.com/Frogging-Family/wine-tkg-git/files/5688513/customization.txt), I have this error [prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5687795/prepare.log).
The rest is just embellishment on my part for explain why I try this configuration...

I forgot mention I am in wine-tkg-git not proton (misstake too)

For hotfixer I speak about this https://github.com/Frogging-Family/wine-tkg-git/commit/3fdd1fd97c71a4a8663df62fe436691d69896b19 but it's just another lack of knowledge about git. Just pass over.

**Comment by Tk-Glitch** [comment]
The hotfix in https://github.com/Frogging-Family/wine-tkg-git/commit/3fdd1fd97c71a4a8663df62fe436691d69896b19 only affects a single staging commit and no other. Unless you manually ask for staging dc77e28, it won't be used. Zebediah fixed it with https://github.com/wine-staging/wine-staging/commit/fd8727a320a67daa4c39fef99f05166856ab07cd following my report.
