### ISSUE TITLE
PSA: I won't release 5.7 based prebuilts

### ISSUE THREAD

**Issue by Tk-Glitch** [Frogging-Family/wine-tkg-git#28]
Due to 5.7 breaking a huge amount of my games and apps I have decided not to release prebuilts based on it for now.

**Comment by SveSop** [comment]
Second that.

Have major issues with 5.7 atm. Completely borks out even on upgrading older wineprefixes for me with `wineboot -u`. 
Also locks up as soon as the character is loading for World of Warcraft. 

I notice debian/ubuntu images was built 21 hours ago, but is yet to be published. Not sure if this is due to some investigation of issues or not (lets hope it is).

**Comment by SveSop** [comment]
In case it is of interest for testing:
[https://source.winehq.org/patches/data/184252](https://source.winehq.org/patches/data/184252)

Posted here: [https://bugs.winehq.org/show_bug.cgi?id=49011#c9](https://bugs.winehq.org/show_bug.cgi?id=49011#c9)

**Comment by SR-dude** [comment]
Usually, a day or two after the release of the staging patches, you tag a release for tkg.  Is this the reason why?

**Comment by Tk-Glitch** [comment]
Absolutely! I might tag a release if things get in a better shape before 5.8 drops.

**Comment by SveSop** [comment]
So far i have not had any specific stability issues after using the patch i linked above.

It is upstream: [https://github.com/wine-mirror/wine/commit/c3fac6e36caab168974dd04a60ae1bbb1a0fd919](https://github.com/wine-mirror/wine/commit/c3fac6e36caab168974dd04a60ae1bbb1a0fd919)

And wine-staging tree is rebased for this aswell.

quick-fix rebase for wine-staging since it does not apply cleanly as it is: [https://github.com/SveSop/wine_patches/blob/master/0013_Threadcontext-5.7-fix.patch](https://github.com/SveSop/wine_patches/blob/master/0013_Threadcontext-5.7-fix.patch)

**Comment by Tk-Glitch** [comment]
5.7 staging r6 combined with our reverting hotfixes (https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git/wine-tkg-patches/hotfixes) felt good enough with most/all big regressions out of the picture. So here we go: https://github.com/Frogging-Family/wine-tkg-git/releases/tag/5.7.r6.g7b0b95ee

Closing :)

**Comment by SR-dude** [comment]
I haven't tried it, because I haven't tried 5.7. But, does Assassin's Creed Odyssey work for you?

**Comment by Tk-Glitch** [comment]
I don't have it. However the regression I was able to observe on AC:Origins is fixed with the combo mentioned above.

**Comment by ebiroud** [comment]
> I haven't tried it, because I haven't tried 5.7. But, does Assassin's Creed Odyssey work for you?

It does for me.
