### ISSUE TITLE
Error when disabling mfplat-streaming-support

### ISSUE THREAD

**Issue by rodrigo21** [Frogging-Family/wine-tkg-git#285]
If I add **-W mfplat-streaming-support** to _staging_userargs in advanced-customization.cfg, I get a error in prepare(), without it's building fine.

I didn't get this error when I built wine 6.1 two weeks ago.

Heres the log:
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5976280/prepare.log)

Here its the error on the terminal:

  -> Changing wine HEAD to the wine-staging base commit...
Note: switching to '4f7e621dc58fd82924e64c695dc61a78c55fd44e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 4f7e621dc58 Release 6.2.
==> WARNING: Hotfix: Fix for mfplat breakage in some games
==> WARNING: Hotfix: Revert bd27af97 to fix many game launchers displaying empty windows (StarCitizen, EGS, Riot Client, Minecraft Dungeons etc.)
  -> Hotfixing...
  -> Applying use_clock_monotonic.patch
  -> Applying childwindow.patch
  -> Applying steam.patch
  -> Applying CSMT-toggle.patch
  -> Applying wine-staging patches...
==> ERROR: Patch application has failed. The error was logged to /home/rodrigo/Curioso/Scratch/TK/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
  -> To use the last known good mainline version, please set _plain_version="" in your .cfg
  -> To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done

**Comment by Tk-Glitch** [comment]
The patchset has been disabled in staging for now: https://github.com/wine-staging/wine-staging/commit/41e15516bde2e7c96fdb229c17140bf52fb05403#diff-940bd9120a9e3bf7d428faea663fa64e5cfca747f2085b600890ea346bc21c40

Since the staging script errors out when you try to disable something that isn't available, your result is expected.

**Comment by rodrigo21** [comment]
Ok. Thanks for answering.
I wanted to disable it because every time wine its updated I have to reinstall quartz with winetricks --force and if I install wmp9 or wmp10 I have to make a new prefix to make the vídeos of the games working again.
Without this patchset this doesn't happen, but I just built wine-staging 6.2 and it's happening again.
Do you know anything about this error?

**Comment by Tk-Glitch** [comment]
It might be due to various changes on the winegstreamer side. Zebediah has disabled the mfplat patchset in staging due to those changes upstream. I have noticed multiple games that required the mfplat patchset before are now having working videos on 6.2 mainline. I suppose the changes might lead to a similar "conflict" as the staging patches with your setup. That's unfortunate.

Which game(s) is(are)affected by that issue?

**Comment by rodrigo21** [comment]
Some Visual Novels. But with 6.2 the wmp videos are still working.
Maybe it's a problem with quartz.

Thanks, I will close the issue.
