### ISSUE TITLE
FSHack and no 1600/1800p

### ISSUE THREAD

**Issue by jarrard** [Frogging-Family/wine-tkg-git#313]
Just wondering where fullscreen hack which tool lower resolutions and scaled to desktop resolution, this is available with proton but not tkg version.  Additionally TKG is missing 1600 and 1800p resolutions! (available in valves proton).

Where are these features in tkg? how do I enable them?

**Comment by Tk-Glitch** [comment]
The fshack can be enabled up to 2aebe0b628a171abd2ffb63054e3d3d0da60dd05 (which is wine 5.21 devel), after which it is enforced as disabled due to deep changes in wine upstream breaking it, requiring a complex rebase. The next proton update will bring rebased patches so we can start supporting the feature again on newer revisions.

We do have both 1600 and 1800p in our fshack patchsets btw: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/proton/valve_proton_fullscreen_hack-staging.patch#L3719 (not having them would be weird considering that https://github.com/ValveSoftware/wine/pull/66 ). But of course it'll only work up to the aforementioned commit id.

If you want to make use of those resolutions with a more recent tree, which lacks fshack support currently, you can add them through xrandr. See https://wiki.archlinux.org/index.php/xrandr#Adding_undetected_resolutions for example.

**Comment by jarrard** [comment]
Cool thanks, but yeah kind of pointless without fshack as it messes up my desktop resolution and sometimes fails to recover.

**Comment by Tk-Glitch** [comment]
As of https://github.com/Frogging-Family/wine-tkg-git/commit/eba7bfda636bc3f6530f815a7295e2425fd1d922 FS hack is back on staging 6.3 to 6.5. More recent changes upstream (rawinput being slowly merged) broke it on 6.6 devel, but that's still much better than having to use 5.20 :frog:

Unsure about the stutters you experience being related to the FS hack. I have tried a few games with it and didn't notice any abnormal stuttering.

**Comment by Tk-Glitch** [comment]
If your stutter issue is related to mouse input, you can try with `LD_PRELOAD="" %command%` as launch parameter. There's a patch that wasn't properly rebased in Proton 6.3 that can lead to stuttery mouse and that launch parameter is a workaround.

**Comment by jarrard** [comment]
> If your stutter issue is related to mouse input, you can try with `LD_PRELOAD="" %command%` as launch parameter. There's a patch that wasn't properly rebased in Proton 6.3 that can lead to stuttery mouse and that launch parameter is a workaround.

I'll give it a shot.

**Comment by SveSop** [comment]
Seems staging 6.6 got rawinput enabled again, with some new patches... So i guess with some trickery it will be made to work again? :)
[https://github.com/wine-staging/wine-staging/commit/661df7b889bb973721d09a316d87d200a31233fe](https://github.com/wine-staging/wine-staging/commit/661df7b889bb973721d09a316d87d200a31233fe)
