### ISSUE TITLE
Cant compile proton-tkg 494e8af

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#327]
Cant compile proton-tkg 494e8af
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6294495/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6294497/prepare.log)
![Screenshot from 2021-04-12 11-56-16](https://user-images.githubusercontent.com/36989404/114353172-2397b580-9b86-11eb-8456-88c7e1e0464e.png)

**Comment by rejedai** [comment]
Same, I tried downgrade to 6.5, but scripts are not tied to wine versions. Personally, I think this is an oversight, because sometimes you need to compile a specific version, but for this you have to edit the configs, which is not very convenient, it would be great if the source code contained the required version in the releases tab.
