### ISSUE TITLE
Since ef4f7a6, rustc can't find libLLVM-11.so, while it really exists.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#361]
![Screenshot from 2021-05-07 07-50-44](https://user-images.githubusercontent.com/36989404/117391226-f3370300-af08-11eb-9e52-40e530e1bd34.png)

**Comment by Kerrung** [comment]
And why is the "rust" package missing from the 'makedepends' section in PKGBUILD?

**Comment by Kerrung** [comment]
I already used llvm 12 compiled myself, but due to the fact that in Arch Linux now rust strictly requires llvm-libs 11 to work, I had to do downgrade, which I did not want to do voluntarily.

**Comment by Tk-Glitch** [comment]
This is due to https://github.com/Frogging-Family/wine-tkg-git/commit/ef4f7a60e88ecf1894b55e7a000e65b547b060ff

Proton's mediaconverter depends on rust. I was kinda in a rush to get it working so it was pushed as soon as I could get RE8 ingame.
The plan is to make it optional and togglable with a .cfg option, so people can disable it if desired. The make dependency will be added dynamically.

**Comment by Kerrung** [comment]
It's still an issue, even with 40f18c0bac68ed6ccdd8564d7ea42a1d936f469e
![Screenshot from 2021-05-08 15-37-08](https://user-images.githubusercontent.com/36989404/117537033-f2d95d80-b017-11eb-9a34-ff1c9d903e88.png)

**Comment by Tk-Glitch** [comment]
I can't reproduce that issue on my end. The toggle to turn off media-converter building will allow you to bypass the issue, but it would be cool to actually fix it.

**Comment by Kerrung** [comment]
Since 89a946d403ad11e32d9b339629addec8db9264bb all works fine, no any errors even with _build_mediaconv="true".
Thank you so much!
Closing as fixed now.
