### ISSUE TITLE
opt build - Wine-tkg-mainline confused by WOW64 prefix

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/wine-tkg-git#371]
Hey there! Recently (since around Wine 6.8), wine-mainline has been getting confused by WOW64 prefixes. From what I can tell, it's preferring 64-bit unless I specifically make a 32-bit prefix. I used a clean prefix both times to test its behavior.

Here's the output of wine --version:

```console
/opt/wine-tkg-git-clean-mainline/bin/wine --version
wine-6.8.r139.gce72f9b4263 ( TkG Plain )
```

WOW64:

```console
$ WINEPREFIX=/home/jeremiah/Games/lutris/wine_test /opt/wine-tkg-git-clean-mainline/bin/winecfg            
wine: created the configuration directory '/home/jeremiah/Games/lutris/wine_test'
wine: could not load ntdll.so: /opt/wine-tkg-git-clean-mainline/bin/../lib/wine/x86_64-unix/ntdll.so: cannot open shared object file: No such file or directory
0024:err:environ:run_wineboot failed to start wineboot c00000e5
wine: could not load kernel32.dll, status c0000135
```

Win32:
```console
$ WINEPREFIX=/home/jeremiah/Games/lutris/wine_test WINEARCH=win32 /opt/wine-tkg-git-clean-mainline/bin/winecfg
wine: created the configuration directory '/home/jeremiah/Games/lutris/wine_test'
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:start_rpcss Failed to open RpcSs service
0040:fixme:file:NtLockFile I/O completion on lock not implemented yet
0040:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0040:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
wine: configuration in L"/home/jeremiah/Games/lutris/wine_test" has been updated.
```

And this is the modified section from the wine-tkg-mainline profile:
```bash
_EXTERNAL_INSTALL="true"
_DEFAULT_EXTERNAL_PATH="/opt"
_EXTERNAL_NOVER="true"
```
I'm not really sure if this is an upstream thing or not, but here it is. Thanks as always!

**Comment by logos128** [comment]
Seems the issue is the external binaries are linked against the previous standard lib paths (../lib/wine/x86_64-unix/ for x86_64, etc.), while the libraries are being relocated during the 'make install' phase to the new style paths which are different (x86_64 in ../lib64/wine/x86_64-unix/ and i386 in ../lib/wine/i386-unix/). So there is a mismatch between the hardcoded link path in the binary and the actual path where the shared library resides. In this case it searches the x86_64 ntdll.so in ../lib/wine/x86_64-unix/, while it resides in ../lib64/wine/x86_64-unix/.

@Tk-Glitch, IMO something like the attached patch should fix it. Haven't tested it thoroughly, but at least x64 Steam (wine-tkg) and another app which uses .NET 4.7.2 worked properly (using the normal way to start wine-tkg with /opt/wine-tkg-staging-fsync-opt-git/bin/wine , etc.)
[fix_ext_install_lib_paths.txt](https://github.com/Frogging-Family/wine-tkg-git/files/6484342/fix_ext_install_lib_paths.txt)

**Comment by CartoonFan** [comment]
@logos128 The patch seems to work for me, at least.

**Comment by Tk-Glitch** [comment]
@logos128 Your solution is pretty much what I had in mind after looking at the issue. Thanks, I'll add your changes.

**Comment by CartoonFan** [comment]
Thanks, everyone!
