### ISSUE TITLE
Some questions about Proton-tkg's user_settings.py

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#378]
https://github.com/Frogging-Family/wine-tkg-git/blob/master/proton-tkg/proton_template/conf/user_settings.py
1)
"PROTON_USE_WINED3D9": "1",
 Why it is a default? Am I right on this point that this default setting means that DXVK still uses wined3d based on OpenGL for d3d9 translation by default, instead of using Vulkan based translation from DXVK? If so, is this not an oversight? Or does the default use of wined3d based on OpenGL have some good reason so far? 

2) 
"PROTON_USE_SECCOMP": "1",
Is it possible to somehow make it turn on by default, but automatically turn off if _use_staging="false", since as written in this description it only works if _use_staging="true"? Or are there good reasons for not enabling this by default too?

**Comment by Tk-Glitch** [comment]
The first one is not default anymore (since early d9vk integration, well before it got merged with dxvk). The default state of the file in the repo doesn't reflect the default settings used at build time.

The second one is legacy and will always be turned on with staging on kinda recent wine trees (6.0+ or something like that). It cannot be disabled on such trees. It has zero effect on legacy non-staging and zero effect on current staging and non-staging. In other words, this setting can be fully ignored on current wine.
