### ISSUE TITLE
Generated .desktop is borked

### ISSUE THREAD

**Issue by terencode** [Frogging-Family/wine-tkg-git#39]
With wine-tkg 5.8 (also happened on 5.7)

`Exec=env WINEPREFIX="/home/terence/.local/share/wineprefixes/wine-audio" wine /usr/bin/wine /Unix /home/terence/.local/share/wineprefixes/wine-audio/dosdevices/c:/ProgramData/Microsoft/Windows/Start\\ Menu/Programs/Genuine\\ Soundware/VB3-II/VB3-II.lnk`

With wine 5.8 from archlinux repo:

`Exec=env WINEPREFIX="/home/terence/.local/share/wineprefixes/wine-audio/" wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/terence/.local/share/wineprefixes/wine-audio/dosdevices/c:/ProgramData/Microsoft/Windows/Start\\ Menu/Programs/Genuine\\ Soundware/VB3-II/VB3-II.lnk`

When I try to run the previous one, I get 
`"0024:err:module:__wine_process_init failed to load L"Z:\usr\bin\wine", error c000012f"`

My config: 

[wine-tkg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/4633843/wine-tkg.txt)

I suspect it's coming from https://github.com/wine-staging/wine-staging/blob/master/patches/winemenubuilder-Desktop_Icon_Path/0001-winemenubuilder-Create-desktop-shortcuts-with-absolu.patch

**Comment by kode54** [comment]
That staging patch does appear to be broken.

**Comment by thehumandistraction** [comment]
I've been experiencing this same issue as well and have been preparing a report regarding it. Here's what I've found so far:

The shortcuts that are created by the Tkg-pkgbuild version of wine is broken 
starting from version 5.7. This happens ONLY when initially created when installing
a new program/creating a new `WINEPREFIX`.

Erroneous Batlle.net shortcut created by Tkg-pkgbuilds 5.7+:

`env WINEPREFIX="/home/thomas/.wine" wine /usr/bin/wine /Unix /home/thomas/.wine/dosdevices/c:/ProgramData/Microsoft/Windows/Start\\ Menu/Programs/Battle.net/Battle.net.lnk`

However, ONLY the previous shortcuts work correctly when wine is upgraded from 
5.6 to a newer version. Strangely, the previous shortcuts are changed after the upgrade: 

Working Battle.net shortcut when initially created in 5.6 but then updated in 5.8:

`env WINEPREFIX="/home/thomas/.wine" /usr/bin/wine C:\\windows\\command\\start.exe /Unix /home/thomas/.wine/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Battle.net/Battle.net.lnk`

This may be due to a `winepath` bug as was fixed for 5.6, see: #17 

For reference, the package available via the official Arch Linux repo creates a 
shortcut with minor differences:

`env WINEPREFIX="/home/thomas/.wine" wine C:\\windows\\command\\start.exe /Unix /home/thomas/.wine/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Battle.net/Battle.net.lnk`

**Comment by Tk-Glitch** [comment]
The issue should now be fixed: https://github.com/wine-staging/wine-staging/commit/102af10c89164cff0be68d6b4072de9050b1000b

**Comment by thehumandistraction** [comment]
Just wanted to confirm that it is indeed fixed.
