### ISSUE TITLE
wineserver High cpu usage

### ISSUE THREAD

**Issue by psychaos999** [Frogging-Family/wine-tkg-git#427]
Hi,
with the latest proton_tkg_6.11.r3.g9bf50b7e.release wineserver use 50+% cpu on a four core. Releases before that used 1/2%.
This is true even for today's wine release.

Hope it helps

**Comment by logos128** [comment]
I can confirm this. Looks like something which involves network sockets, since WINEDEBUG=+server shows very high rate of repeatable messages caused by a network socket which is trying to communicate unsuccessfully, then a "reselect" is called which repeats the previous again and again in an infinite loop. In my case it utilizes 100% of the core on a six core processor with hyperthreading.

Can be reproduced in Steam (wine) on the Library tab. The high activity starts after ~5min - 8min. Then it can be stopped (for a while) switching to the Store tab. IMO this closes the offending socket and the polling stops.

From my testing Wine Staging 6.8.r0 is unaffected, while 6.8.r13 (I have an old build) is already affected. Both staging and mainline show the problem. Probably needs to be bisected and reported upstream.

BTW, with the latest versions of wine 6.9+, Steam (wine) experiences high difficulties to connect to steam network with almost 50% unsuccessful rate. Initially I thought could be a problem with the steam network in my region, but then tested Steam (proton) and Steam (windows) and it worked as usual. Now, while testing this issue, with wine-tkg 6.8 it connects to steam network very reliably. So there seems to be something with the networking code (ws32/wineserver) with the latest releases.

**Comment by Tk-Glitch** [comment]
Could you please try deleting this file in your tree: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/hotfixes/a70c517/networking_fix.mypatch
Then rebuild and see if that fixes your issue.

**Comment by logos128** [comment]
@Tk-Glitch 
Seems it's not being applied in my case. I'm building 6.8+ which is earlier than a70c517. It might be the cause for the networking issues with recent releases though, so I'll look into it.

Anyway, I've found the rebase commit on staging which is causing the high cpu activity with wineserver. It's 6.8.r12: https://github.com/wine-staging/wine-staging/commit/ab2f8734d90752be2f2551ffd0eb8834224f9ade
Later today will look into mainline commits from that day and hopefully will find the one causing the issue :)

**Comment by logos128** [comment]
Found out the mainline commit that causes the excessive cpu usage in wineserver. It is https://github.com/wine-mirror/wine/commit/737fe1f99337ab999cf67fb1acdf96f70020b3d4

Fortunately it can be reverted on the current master without any problems. Tested it for longer period (1h+) on 6.11 without any issues with wineserver - no more high cpu utilization.

IMO it should be reverted until the upstream fixes the issue.

**Comment by logos128** [comment]
@Tk-Glitch 
I've tested this further, and while the commit https://github.com/wine-mirror/wine/commit/737fe1f99337ab999cf67fb1acdf96f70020b3d4 is causing the excessive cpu usage from wineserver, it seems to be needed at least for the proper functioning of the CEF component used in Steam. With other words Steam (wine)'s Store tab stops functioning properly, as well as some of the individual game pages. Tested it on both 6.10 and 6.11 mainline, and on 6.11 staging with the same results.

So, hold on for now on reverting that commit.

Probably the best way for us is to report this to upstream and wait for them to fix it. I'm pretty sure that it's part of the performance regression/high temps problem reported lately.

**Comment by Tk-Glitch** [comment]
Thanks for bisecting @logos128 ! Yeah this is a clear candidate for upstream reporting. Weird that it's not affecting everyone. *Maybe* we could revert it for Proton only as a temporary workaround. I'd need to check if the most used launchers are still working nonetheless.

**Comment by SveSop** [comment]
I am experiencing huge difficulties with World of Warcraft and wine-(staging)-6.10+6.11. Stuttering and stalls and extremely high pings/disconnects (6K+). This also happens with (upstream) wineHQ distributed wine-staging, so afaik it is a upstream issue.

Have tested various mix of patches from here to see if it solves that, but to no avail. Back to 6.8 everything is smooth as butter with 30'ish ping ingame and no stalling.

**Comment by Tk-Glitch** [comment]
I have added a hotfix with a prompt with https://github.com/Frogging-Family/wine-tkg-git/commit/891d5362ea2dd394cb9cfdd76c7e5608990c0886

The prompt will only show up by default on wine-tkg, and will be skipped on proton-tkg. Setting `_hotfixes_no_confirm="false"` instead of `_hotfixes_no_confirm="true"` in your proton-tkg .cfg file will make the prompt show up for the ones unaffected by the issue who wouldn't want the hotfix applied.

Thanks again to @logos128 for bisecting. This is not meant as a fix of course, and will need a proper one upstream, but it should at least make things usable for the people affected by the issue while we wait.

Since Zebediah is the author of the patch, I'll let her know about it as well.
