### ISSUE TITLE
Kernel 5.15 breaks the wine server

### ISSUE THREAD

**Issue by SR-dude** [Frogging-Family/wine-tkg-git#507]
So, I tried the new release candidate for kernel version 5.15. I wanted to try the new ntfs driver. All seem well until I tried to start up the windows client of steam. The client never appeared. The log-in box did and allowed me to type in my password. I hit [login] and nothing happen after that. It just seem to die without warning or reason. Downgrading to 5.14 fixed the problem.

**Comment by Tk-Glitch** [comment]
Was fsync enabled? If so, could you please try with it disabled? Thanks

**Comment by SR-dude** [comment]
No, fsync isn't enabled.

**Comment by Tk-Glitch** [comment]
Then it's an upstream issue with the kernel. Not totally unexpected for a first RC tbh :stuck_out_tongue:

**Comment by aufkrawall** [comment]
Is the prefix on an ntfs drive mounted with ntfs3? It's giving me weird file access issues after some time (maybe due to booting of Windows in between?). Unless my mount options aren't optimal (`uid=1000,gid=1000,umask=000`), I'd rather recommend to stay away from it (and ntfs-3g with Linux file system rights management causes slow downs in games with even hardly any I/O activity).

I can check again, but I'm rather certain that starting Steam in Wine prefix from ext4 partition works as expected.

**Comment by SR-dude** [comment]
No, the prefix is on my root partition(ext4).

**Comment by SR-dude** [comment]
With the latest release candidate, it is fixed. Closing.
