### ISSUE TITLE
The Elder Scrolls IV: Oblivion (22330) greys out play button with proton_tkg_6.19.r1.g5e9626af

### ISSUE THREAD

**Issue by sonic2kk** [Frogging-Family/wine-tkg-git#543]
System Information:
- OS: Arch Linux w/ KDE Plasma
- Kernel: 5.14-9-arch2-1
- CPU: AMD Ryzen 3700X
- GPU: AMD RX 5700XT
- RAM: 16GB

Attempting to run a vanilla Oblivion installation with `6.19.r1.g5e9626af`, the launcher displays greyed out options. The problematic ones are Play and Options. This does **not** happen with Proton 6.3-7, Proton Experimental or Proton-6.18-GE-2. The launcher and game launch correctly with these versions. I deleted the prefix between each Proton version test.

![Screenshot_20211010_231627](https://user-images.githubusercontent.com/7917345/136715117-b8ca3ff6-f5fa-482e-8167-4429f72421b0.png)

I renamed `Oblivion.exe` to `OblivionLauncher.exe` in an attempt to bypass the launcher. This produced an "Application load error", something that seems to happen with the game on Windows but the fixes, no surprise, did not work on Linux :-) This error does **not** occur with Proton 6.3-7, Proton Experimental or Proton-6.18-GE-2.

![Screenshot_20211010_234006](https://user-images.githubusercontent.com/7917345/136715356-4c0235f7-9dd4-492b-b1ca-440fbc8456ac.png)

(Note: The Application load error message **also occurs** with `proton_tkg_6.17.r0.g5f19a815.release` if `Oblivion.exe` is renamed to `OblivionLauncher.exe`, though that is probably best tracked in a separate issue.)

At the time of writing, the most recent release version of Proton-tkg is `proton_tkg_6.17.r0.g5f19a815.release`, and this **does** work. However, the launcher crashed when I initially attempted to use it. I had to launch another game first before I was able to get Oblivion to launch with this release. I'm unable to reproduce the crash, so unfortunately I cannot provide a log file.

If any additional information or testing is required I am more than happy to provide it.

**Comment by Tk-Glitch** [comment]
After some investigation, here are initial results.

- The "greyed out" buttons issue is actually due to a missing registry entry. It seemingly can happen on any proton version but the actual reason is unknown. You can fix it by adding the entry manually in your prefix's system.reg:
```
[Software\\Wow6432Node\\Bethesda Softworks\\Oblivion] 1633972009
#time=1d7bec260fea335
"Installed Path"="Z:\\Games\\SteamLibrary\\steamapps\\common\\Oblivion\\"
```
(adapt the path to your own game path)

- The App error 65432 and/or 65434 are steamapi related, and while the former might simply be due to a dependency to the launcher, the latter is triggered by the proton steamclient swap not getting triggered, resulting in the game trying to load windows native steamclient.dll, which won't work with proton. This issue affects only some 32-bit games, and the reason is unclear as GE is using my steamclient swap patchset. It also used to work fine, which makes it even weirder.
