### ISSUE TITLE
Proton applies plain-wine patches

### ISSUE THREAD

**Issue by veganvelociraptor** [Frogging-Family/wine-tkg-git#572]
Is there any way to disable plain-wine patches ../wine-tkg-git/wine-tkg-userpatches//*.mypatch being added when compling wine-proton-tkg?

The behaviour seems to have changed since I last compiled proton-tkg, and it insists in re-compiling wine that I just had compiled by myself a while ago, whenever I try to compile proton-tkg. And since I have amdags.mypatch added to wine-tkg, it fails to compile, since proton requires amdags-proton.mypatch and not amdags.mypatch.

What's the reason for not compiling a standalone proton-tkg like it used to and use the patches from proton-tkg-userpatches?

**Comment by Tk-Glitch** [comment]
> What's the reason for not compiling a standalone proton-tkg like it used to and use the patches from proton-tkg-userpatches?
It never was that way actually. Proton-tkg is just a wrapper for wine-tkg-git build system and since wine userpatches are only affecting the wine side of things, the compatibility shift is just a matter of configuration. Proton is still just wine in the end.

Dropping those amdags patches inside the userpatches dir is not the way you're supposed to use the community patches. There is a specific `_community_patches` option in both wine and proton-tkg .cfg files made to hold your community patches list so you can have different configurations for both if needed. If you wanted to use external patches not found in the community-patches repo for which you'd also need to be selective regarding plain wine or proton application, you could drop them in the community-patches repo dir and enable them as opt-ins through .cfg like other community patches.

The userpatches dir is really more of a developer-oriented feature where you can drop a patchset or many in there and test your patch(es) quickly with no need for configuration.

**Comment by veganvelociraptor** [comment]
Thank you for taking your time explaining. Much appreciated!
