### ISSUE TITLE
Proton ntdll-Syscall_Emulation patch apply failure

### ISSUE THREAD

**Issue by Spoons** [Frogging-Family/wine-tkg-git#591]
The ntdll-Syscall_Emulation patch fails to apply. Default settings, staging.

```
     Staging overrides used, if any: -W ntdll-NtAlertThreadByThreadId -W ntdll-Junction_Points -W server-File_Permissions -W server-Stored_ACLs -W winex11-WM_WINDOWPOSCHANGING -W winex11-_NET_ACTIVE_WINDOW
 ==> ERROR: Patch application has failed. The error was logged to /home/username/build/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
```
```
Applying /home/username/build/wine-tkg-git/wine-tkg-git/src/wine-staging-git/patches/ntdll-Syscall_Emulation/0001-ntdll-Support-x86_64-syscall-emulation.patch
error: patch failed: configure:7465
error: configure: patch does not apply
ERROR: Failed to apply patch, aborting!
```

I'm curious as to how you look into this. Typically a patch failure specifies which hunks fail to match.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/20352749d42644b40506a29513ed31515d28fd15

**Comment by Tk-Glitch** [comment]
As to how I'm looking into this, since it's a staging patch application failure it's either upstream or something we're doing to staging. The prepare.log shows that one of our hotfixes is touching the problematic file, and testing without that hotfix applied doesn't trigger the issue. So I now know I just have to rebase the hotfix against upstream changes.
