### ISSUE TITLE
Hotfix to revert upstream d171d11 for nvidia users?

### ISSUE THREAD

**Issue by mitchell-gil96** [Frogging-Family/wine-tkg-git#600]
Hi, commit d171d1116764260f4ae272c69b54e5dfd13c6835 published in upstream 6.12 seems to cause Xorg to go to 100% single core cpu usage with nvidia cards on proprietary driver.

Upstream bug report:
https://bugs.winehq.org/show_bug.cgi?id=51420

Link to githubb mirror of commit:
https://github.com/wine-mirror/wine/commit/d171d1116764260f4ae272c69b54e5dfd13c6835

I was wondering if it's possible to please add a patch or hotfix to revert this specific commit on tkg build? If the patch exists, I'm sorry for duplicate request.

**Comment by gardotd426** [comment]
I'm assuming this must be limited to older cards on older drivers, cause people in that bug thread that don't have old cards requiring old drivers don't see the issue anymore, and I've actually never seen it. 

I have an RTX 3090 and I got it on launch day (over a year ago, Sept. 24 2020), and I've ran wine programs literally every day since then. I've never had CPU usage go to 100% because of Wine (except when starting a new game using DXVK and shaders are compiling for like 2 seconds). 

I just ran `sudo perf top -p $(pgrep Xorg)`, and watched it as I started some wine programs, and nothing changed. Nvidia was at like 15-20%. 

Any hotfix reverting this might need to actually check what drivers the user is on to avoid reverting it on unaffected GPUs/drivers.

**Comment by mitchell-gil96** [comment]
RTX 2060 on the latest drivers provided by the official arch repos.

Actually the common denominator in that bug thread seems to be multi-monitor setups rather than "old cards and old drivers" as assumed. Since Nvidia multi-monitor setups running wine are relatively rare, it would make sense that that specific bug hasn't gained traction.

**Comment by gardotd426** [comment]
>Actually the common denominator in that bug thread seems to be multi-monitor setups rather than "old cards and old drivers" as assumed. Since Nvidia multi-monitor setups running wine are relatively rare, it would make sense that that specific bug hasn't gained traction.

I have 2x 1440p 165Hz monitors. I've actually ran dual monitors since long before this machine had an Nvidia GPU in it, and have ran dual monitors every day I've had it. So that's not it. 

The problem is that that commit fixed several rendering issues in games that people were having, so just blindly reverting it might reintroduce the issue (and I don't believe the original bugs were even limited to Nvidia, so it could even reintroduce issues for Nvidia users). 

I guess the best solution might be to ask the user during compilation whether they want to revert the commit, the same way it currently does for restoring the PulseAudio patchset and re-enabling mfplat, during the hotfixer stage.

Either that or put it in `wine-tkg-profiles/advanced-customization.cfg`.

**Comment by mitchell-gil96** [comment]
I would be okay with an option in advanced-customization.cfg 

This specific commit has been identified as the culprit and i just need an option to revert it. Most people would probably run TKG fine without it, but the option to revert would be valuable.

**Comment by gardotd426** [comment]
Here @mitchell-gil96 test this patch out (unzip and put in `wine-tkg-git/wine-tkg-userpatches/`). 

If it fixes it I'll file a PR to add it to `community-patches`. 

[patch.zip](https://github.com/Frogging-Family/wine-tkg-git/files/7632134/patch.zip)

You have to use `_plain_version="f37fe9c"` and `_staging_version="65ca056"` if you want to build before TKG fixes #607 / #608 

But I just tested and the patch applies and the build completes fine, and the completed build works (obviously I can't check if the bug is fixed since I can't reproduce it). 

Please let me know.

**Comment by mitchell-gil96** [comment]
@gardotd426 Thank you so much! Building with the patch against the specific versions posted did the trick! Xorg down to about 3% cpu usage and my system doesn't become unusable anymore when running any wine app.

Just to be clear, if/when #608 gets fixed, I no longer have to specify plain version and staging version correct? Those two are temporary workarounds for that separate tkg-specific issue?

**Comment by mitchell-gil96** [comment]
I'll track #608 as well, but in the meantime thank you again @gardotd426!
I'll close this issue now.

**Comment by gardotd426** [comment]
@mitchell-gil96 yes, when #608 gets fixed you can remove those version tags. It's just that there's been an update upstream that broke the hotfixer, it'll get fixed in the next day or so I'm sure. 

I'll go ahead and file a PR with the community patches repo. Once you see that get added, go ahead and remove it from `wine-tkg-userpatches` and just add the name of the patch to the `community_patches` array in `customization.cfg`.

**Comment by gardotd426** [comment]
@mitchell-gil96 watch for `revert_return_correct_color_depth_for_display_DCs_in_GetDeviceCaps.mypatch` to get added to the community-patches repo. PR filed.
