### ISSUE TITLE
Error: ntoskrnl

### ISSUE THREAD

**Issue by MalonnBethesda** [Frogging-Family/wine-tkg-git#706]
First off, I haven't notcied any issues with any applications yet that I don't know what they are.  Having said that, I am getting two errors, the first of which is the title.
```
0084:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
```
Next, I get
```
0124:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0124:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
```
For the second, I read the "winbind" package may fix it, but I believe I've tried it without success.
I'm on 7.2, Linux Mint MATE 20.3.  Nvidia.

**Comment by Tk-Glitch** [comment]
For `err:ntoskrnl:ZwLoadDriver failed to create driver`, it seems to be currently expected. I can reproduce this on plain wine-staging for months now. It doesn't seem to be much of a problem right now.

Regarding the second part, `ntlm_auth --version` will tell you the currently installed version of the tool, if installed. It's part of the samba suite, so depending on your distro it could be part of the samba package instead of winbind. That being said, it's usually considered as a non-issue unless you get actual networking issues in your app/game.

**Comment by MalonnBethesda** [comment]
Good to know @Tk-Glitch

I searched the first error and it appears to be related to a program that writes bootable thumb drives from discs.  No biggie.

The second issue I checked, and ntlm_auth is not installed on my distro by default.  So I can install it, or just live with the error until I play a game that accesses the internet.  Which I don't right now outside of steam.

Thanks for the help.
