### ISSUE TITLE
sorry, newb question about changes/wine-tkg install

### ISSUE THREAD

**Issue by linuxgirl22** [Frogging-Family/wine-tkg-git#71]
Hello :-)
Sorry to be such a newb with this, but I'm not sure, on reading about the changes, if it means users need to build certain modules now? 

I'm testing EndeavourOS on Asus Tuf laptop (AMD Ryzen R5-3550H, AMD Radeon RX560X 4GB, 16 ram), running the latest Zen kernel. Am testing to see about running Endeavour on main PC (AMD Ryzen 7 3800X, AMD Radeon RX 5700 XT, 32 ram). I usually enable the chaotic-aur in pacman.conf, for the duration of the install, installing wine-tkg-fsync-vkd3d-git. I don't know whether there was an internet glitch or what, but the download took about 30 minutes. There was a fail notification at the end, so I reinstalled, but message said already installed/reinstalling. Unfortunately, on rebooting, there's a message saying lightdm can't run, and I can't get back into that system. 

It's way beyond my abilities to get into deeper work with wine, and I've really appreciated being able to install wine-tkg-fsync-vkd3d-git. I understand it stops the frame rates being locked at 20 fps ... if it is that things have shifted to more user-interactive regarding this package, may I be so bold as to ask which non-user-interactive version of wine there is that would unlock frame rates?

EDIT: I've just seen you saying on Reddit about needing to stay on kernel 5.6 at this point ... ?

**Comment by Tk-Glitch** [comment]
There seems to be a bit of confusion here.
First of all, `wine-tkg-fsync-vkd3d-git` doesn't interact with `lightdm`. It's more likely an issue with another package, possibly mesa or the kernel. Long download time might have been due to the servers or network encountering some kind of issue, and that can lead to corrupted packages. I'm not working on nor maintaining chaotic-aur so you might want to have a look on their end here: https://github.com/chaotic-aur/infra .

> I understand it stops the frame rates being locked at 20 fps

That confuses me. I can see that happen on some cases with esync/fsync, but it's not a general rule. If possible, please give more details.

> if it is that things have shifted to more user-interactive regarding this package

Unless you want to build it yourself (meaning not through chaotic-aur), which don't seem to be what you want, there's no change.

> EDIT: I've just seen you saying on Reddit about needing to stay on kernel 5.6 at this point ... ?

Confusing times when kernel and Wine versions are crossing. Wine and the kernel are two very different things. My message on reddit was about **Wine** 5.6, but by using -tkg builds you bypass the issue. It was specifically regarding vanilla versions.

Did you install anything else before rebooting besides Wine? I'd check specifically for mesa and the kernel. More detail on the error message - if it outputs anything - might also be helpful.

**Comment by linuxgirl22** [comment]
Thank you very much for such a helpful response, and, yes, it sounds very possible that the package corrupted ... as soon as I'd started reboot, the screen went black with a flashing underscore in the top left, which had seemed odd. 

Thank you for the link to chaotic-aur. I can't see anyone reporting anything similar, so package corruption seems to stand out more. 

About the 20 fps being unlocked, I read that on reddit in connection with esync ... [https://www.reddit.com/r/wine_gaming/comments/8vf1ka/what_is_wine_esync_and_how_should_i_set_it_up/](url)

![20 fps comments](https://user-images.githubusercontent.com/35760727/86097042-a5a96880-baa3-11ea-9597-942b99bf3e54.png)

Thank you very much for assurances that things haven't changed about install, and I understand your Reddit comment properly now. 

I'd done the net install of Endeavour (Mate), a few software installs, and switched to the Zen kernel.  Will reinstall endeavour, install Zen, then downgrade it back to 5.6, and report back. Thanks so much again.

**Comment by linuxgirl22** [comment]
Hi again :-) 

Managed to get it installed. Downgraded zen kernel to 5.6. Added chaotic-aur. This time used Pamac; selected various options, error message about a 'zap' dependency, re-selected options and install began. Really fast up until the actual wine-tkg. That took about 25 minutes, then everything else installed fine.
 
I think I'd goofed up with the terminal install before, and am not sure if there's a server issue or if there's a setting in endeavour; will ask on the forum about any differences from Anarchy install, that could possibly cause slow downloads. Another install, numix-icon-theme-git, had stuck for 15 minutes, also, which made me wonder if it's an arch/repo/endeavour issue.

**Comment by Tk-Glitch** [comment]
Depending on your country, you might be hitting a slow path regarding default used mirrors. You may want to have a look there: https://wiki.archlinux.org/index.php/Mirrors

Also regarding chaotic-aur the order of the servers will affect priority. If it's always slow for you, reordering to have a different mirror first might help.

**Comment by linuxgirl22** [comment]
Many thanks @Tk-Glitch :-) Will make sure about checking and reordering mirrors, and thanks for the link too.

**Comment by Tk-Glitch** [comment]
Closing :smile:
