### ISSUE TITLE
[QUESTION] compile old version, wine 5.6.1

### ISSUE THREAD

**Issue by chorriwuarri** [Frogging-Family/wine-tkg-git#78]
noob question

if I compile an old version of wine/proton, for example 5.6.1

would this version use the latest proton patches?

**Comment by Tk-Glitch** [comment]
It'll vary by patchset and by version. The guarantee is having the latest available at the time that version got released, and if it happens to get newer additions over time it's a bonus. Patchset rebase usually happens when there's breakage happening due to upstream changes.
There were rare exceptions were some changes got backported due to refactoring or newly introduced bugfixes.
Rebasing on each addition against virtually all wine versions isn't realistic, and even less so for the simple single human being that I am.

So I'd say it's usually not something you should expect, but if you're not targeting a really old version it's actually very likely.

Do you have a specific patch/patchset in mind? I could tell you if it's in or not pretty easily.

**Comment by chorriwuarri** [comment]
thank you for replying
I had nothing in mind or specific, it was something more general
because with the latest versions of wine/proton, I have some problem with some specific game, but I just compiled wine and proton pointing to the version of stagin v5.6.1 and everything seems to be fine

I think you do a great job, you are one of the reasons why I use linux to play and not windows, I use your kernel, wine/proton and nvidia drivers, so thank you very much

**Comment by Tk-Glitch** [comment]
You're welcome! Out of curiosity, which game is it? The downside of being in sync with upstream is that we also can get hit by upstream regressions. And with the big refactoring of ntdll came other funzies :frog:

**Comment by chorriwuarri** [comment]
overwatch doesn't work for me since wine 5.10, I haven't tried 5.12 yet
with proton 5.9 I had performance problems in elite dangerous, with proton 5.11 it runs amazing

with 5.6.1 seems to be going well, but I need to run more tests

**Comment by Tk-Glitch** [comment]
Supposedly Overwatch works on our hotfixed 5.12 as of https://github.com/Frogging-Family/wine-tkg-git/issues/76#issuecomment-653781914

**Comment by chorriwuarri** [comment]
I'm going to try
I think the raw input patch is broken with my wine compilation

In overwatch, mouse sensitivity is crazy.

**Comment by Tk-Glitch** [comment]
Apparently the report of Overwatch working on 5.12 was false, or it needs a quirk of some kind that wasn't shared with me. Sorry about that.
Regarding mouse, the game has always had issues with it since it first started to work... Maybe worth trying switching between fullscreen/borderless or disabling rawinput altogether.

**Comment by Tk-Glitch** [comment]
Or maybe Overwatch works. I don't know anymore :frog: It seems to be playful.

**Comment by chorriwuarri** [comment]
Yeah, I just tried it and overwatch doesn't work for me with wine 5.12

I found a miraculous backup of wine 5.6 and overwatch works well with it, including the mouse, it already has a normal sensitivity

**Comment by Tk-Glitch** [comment]
For 5.12, I got a report of it working when setting wine version to win8 or win10, while breaking when using win7. If that helps.

**Comment by chorriwuarri** [comment]
Thanks, I used it with win10 and it didn't work, but I'll try it with win8

if it doesn't work I'll use my old wine 5.6  just for overwatch, for me it's no bother

**Comment by chorriwuarri** [comment]
hello
I want to confirm that overwatch runs with wine 5.12
for me it does not run when I run the game directly but through battlenet it works

I apologize for assuring you that it didn't work out

**Comment by Tk-Glitch** [comment]
Oh that's interesting! Thank you for sharing your findings :) How's the mouse behavior?

**Comment by chorriwuarri** [comment]
the mouse behaves the same as in windows, it has the same sensitivity

**Comment by Tk-Glitch** [comment]
Great news! Thanks. I assume I can close?

**Comment by chorriwuarri** [comment]
sure, wine 5.12 works very well, thanks :)
