### ISSUE TITLE
MangoHud prevents games from launching 

### ISSUE THREAD

**Issue by nutta-git** [Frogging-Family/wine-tkg-git#79]
Proton Version: `proton-tkg-5.12.r4.g21a97e1f`

Description: 

- Launching a game using the launch command `mangohud %command%` prevents said game from launching. 

This isn't reproducible with vanilla proton. 

Tested game is _Tom Clancy The Division_ (steam # 365590) 

[FullLog.log](https://github.com/Frogging-Family/wine-tkg-git/files/4884565/TCTDTP.log)
[greped-for-err.log](https://github.com/Frogging-Family/wine-tkg-git/files/4884566/TP.log)

**Comment by Tk-Glitch** [comment]
I can't reproduce the issue on a dozen games tested :thinking:

**Comment by nutta-git** [comment]
@Tk-Glitch are you getting the same error 
`48921.269:0020:00b0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.`
if not, do you know what it is?

**Comment by Tk-Glitch** [comment]
I do see it in my logs but the games are working.

https://bugs.winehq.org/show_bug.cgi?id=48647

**Comment by nutta-git** [comment]
this is not a major issue, so I will just use dxvks hud for the time being. i will report back if anything changes.

**Comment by robzombie91** [comment]
Works fine for me

**Comment by nutta-git** [comment]
@robzombie91 since its working for you, can you check if the package `gcc-c++.i686 ` is installed on your system. 

How to*
`dnf search installed gcc-c++.i686`

**Comment by robzombie91** [comment]
Im only using mangohud on vulkan/dxvk enabled games

**Comment by robzombie91** [comment]
Also im launching mine with wine-tkg, not proton

**Comment by nutta-git** [comment]
Oh, my inquire was about proton-tkg not wine-tkg, but thanks for looking into this.

**Comment by Tk-Glitch** [comment]
Could it be due to the recent winevulkan updates upstream? If you're not already using it, it might be worth trying the -git version of mangohud.

**Comment by nutta-git** [comment]
Compiled mangohud yields the same results as the rpm package.

**Comment by nutta-git** [comment]
@Tk-Glitch I just downloaded `wine-tkg and proton-tkg 5.6.1.hotfix.r0.g4c160ec8` and mangohud is working fine with it. 
now i am going to work my way up the "proton ladder" and report back

**Comment by nutta-git** [comment]
Results: 

-wine-tkg and proton-tkg 5.10.r0.g8648971f = `Pass`
-wine-tkg and proton-tkg 5.11.r0.g3d9a9272 = `Pass`
-wine-tkg and proton-tkg 5.12.r1.g3f3a05f9 = `Pass`
-proton_tkg_5.12.r9.gf6954e6e= `Failed`

**Comment by Tk-Glitch** [comment]
Hmm.. Sounds like winevulkan to me.

> -wine-tkg and proton-tkg 5.12.r1.g3f3a05f9 = Pass

I assume we're talking about the prebuilt release?
I'll make a build against current HEAD for you to try.

**Comment by nutta-git** [comment]
they were the pre-built releases.

**Comment by nutta-git** [comment]
Update: Issue is still present with arch. 
`proton_tkg_5.12.r21.gc3c5d48b  `

**Comment by Tk-Glitch** [comment]
Sorry for the delay I've been quite busy.
Any difference with the release build?
https://github.com/Frogging-Family/wine-tkg-git/releases/tag/5.13.r1.g26d3815d

**Comment by nutta-git** [comment]
No problem, thanks for getting back. 
It looks like this build has the same issue. 
[steam-365590.log](https://github.com/Frogging-Family/wine-tkg-git/files/4952290/steam-365590.log)

**Comment by Tk-Glitch** [comment]
Ok I was able to reproduce the issue. It crashes very early on. It's also exactly the same on a plain wine-staging build from Arch repos so it's not due to a customization from wine-tkg. The mesa overlay (and other vulkan layers tested) works just fine. Looks like either an upstream regression or something mango will have to fix/adapt to.

@flightlessmango Pinging since I couldn't find a corresponding issue on your end. I wasn't able to get anything useful out of the wine logs but maybe you have some idea/direction?

**Comment by aufkrawall** [comment]
For whatever weird reason, I'm having this or a similar issue since I've replaced the GTX 1070 with trusty old Polaris card again. So far it seems to be limited to some 32 bit applications, such as native Windows version of Steam.
I've built mangohud with `-Dwith_xnvctrl=disabled` and  `-Dwith_nvml=disabled`, but that only makes some file load error verbosity disappear, while not actually helping the program to start successfully.

**Comment by aufkrawall** [comment]
It works here when using `MANGOHUD=1` instead of `mangohud`. :)

**Comment by nutta-git** [comment]
Seems like with 'proton_tkg_5.14.r3.geb32fd78' games are running with mangohud enabled. Thank you TKG!

**Comment by Tk-Glitch** [comment]
The winevulkan cleanup must have something to do with it. Nice!

**Comment by aufkrawall** [comment]
It's unfortunately back for me with recent builds for some reason: I can't start Steam in Wine with either `mangohud` or `MANGOHUD=1` and also Strange Brigade doesn't start in protok-tkg, while it does in regular Proton. :(

**Comment by nutta-git** [comment]
Games run fine on my end with mangohud and `proton_tkg_5.15.2.r6.g663c3ba4`

**Comment by aufkrawall** [comment]
There are these errors when I try to start Steam in wine + mangohud:
`mangohud wine Steam.exe
002c:fixme:winediag:__wine_start_process Wine TkG 5.15 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
WARNING: radv is not a conformant vulkan implementation, testing use only.
0048:fixme:seh:dwarf_get_ptr unsupported encoding 9b
0048:fixme:seh:dwarf_get_ptr unsupported encoding 77
0048:fixme:seh:dwarf_get_ptr unsupported encoding 07
0048:fixme:seh:dwarf_get_ptr unsupported encoding 7d
0048:fixme:seh:dwarf_get_ptr unsupported encoding 9b
0048:fixme:seh:dwarf_get_ptr unsupported encoding 77
0048:fixme:seh:dwarf_get_ptr unsupported encoding 07
0048:fixme:seh:dwarf_get_ptr unsupported encoding 7d
0048:fixme:seh:dwarf_get_ptr unsupported encoding 9b
0048:fixme:seh:dwarf_get_ptr unsupported encoding 77
0048:fixme:seh:dwarf_get_ptr unsupported encoding 07
0048:fixme:seh:dwarf_get_ptr unsupported encoding 7d
0048:fixme:seh:dwarf_get_ptr unsupported encoding 9b
0048:fixme:seh:dwarf_get_ptr unsupported encoding 77
0048:fixme:seh:dwarf_get_ptr unsupported encoding 07
0048:fixme:seh:dwarf_get_ptr unsupported encoding 7d`

It also doesn't start when using libstrangle instead of mangohud, but there aren't such errors then.

**Comment by Tk-Glitch** [comment]
> Strange Brigade doesn't start in protok-tkg, while it does in regular Proton
That one interests me. Thanks, I'll investigate.

**Comment by aufkrawall** [comment]
> > Strange Brigade doesn't start in protok-tkg, while it does in regular Proton
> 
> That one interests me. Thanks, I'll investigate.

Thanks for your help! Though that's only the case when utilizing mangohud or libstrangle, it starts fine without them in proton-tkg. :)
I'd really like to get to the bottom of this nasty issue. :(

**Comment by Tk-Glitch** [comment]
Oh. My bad. Okay :sweat_smile: 

What we know so far:
 - It happens with Arch's wine-staging package.
 - It reportedly only happens with mesa (possibly even only with RADV - that could be tested)
 - I could find various unrelated reports with similar outputs when using DXVK

**Comment by aufkrawall** [comment]
Yep. I also tested with non-staging wine from Arch repo and a clean wine prefix without DXVK installed, but not avail.
Sames goes for forcing amdgpu-pro Vulkan globally via env. :(
I'd say it seems to hang/freeze really early, as it doesn't seem to even update the wine prefix when wine has been updated in the meantime.

**Comment by aufkrawall** [comment]
Seems vkbasalt does not trigger this issue.

**Comment by aufkrawall** [comment]
I can successfully run `mangohud wine Steam.exe` when I started winecfg before. However, Strange Brigade crashes then:
`wine: Unhandled page fault on read access to 0000000000000000 at address 00007F5441CFF718 (thread 04f0), starting debugger...`

**Comment by aufkrawall** [comment]
For whatever weird reason, it works when vkbasalt is active at the same time. I checked my user and system-wide implicit and explicit Vulkan layers, but didn't notice anything that I would suspect to make it break. I wonder if this is a bug in some Vulkan initialization part of Wine.

**Comment by nutta-git** [comment]
I guess that's why it was working for me I guess, 
I was using VkBasalt with Mangohud

**Comment by aufkrawall** [comment]
Some progress: The issue was introduced with regular Wine 5.11. Steam starts normally with mangohud and both wine 5.10 and wine-staging 5.10, but hangs with both wine 5.11 and wine-staging 5.11 (and newer versions; tested with builds from Arch archive).

Now to reading 5.11 release notes to hopefully find a clue...

**Comment by DadSchoorse** [comment]
iirc someone on VKx bisected this already, with the first bad commit being https://github.com/wine-mirror/wine/commit/145cfce1135a7e59cc4c89cd05b572403f188161. Also disabling the mesa device select layer with `NODEVICE_SELECT=1` fixes it according to them.
I have no idea what's going wrong here with the combination of that commit + mangohud + mesa device select, and even less of an idea why enabling vkbasalt would workaround it.

**Comment by aufkrawall** [comment]
Thanks, it indeed works that that Mesa variable.

**Comment by Caffe1neAdd1ct** [comment]
Same bisect i've done on wine: https://bugs.winehq.org/show_bug.cgi?id=49441

**Comment by lystrosaur** [comment]
When i type in "mangohud %command%", or "MANGOHUD= 1 %command%", my games fail to launch.I am on ubuntu 20.10 and using newest proton.

**Comment by lystrosaur** [comment]
Nevermind, forcing the game to use a specific version of proton, that is under 5.12, fixed the issue. Hope this helps.

**Comment by nutta-git** [comment]
@lystrosaur have you tried running the game with vkbasalt? I am currently using mangohud with vkbasalt and it works with proton expeimental

**Comment by nutta-git** [comment]
Closing, Issue seems to be [fixed](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3801).
