### ISSUE TITLE
Stripping binaries inside build functions break -debug packages

### ISSUE THREAD

**Issue by Thaodan** [Frogging-Family/wine-tkg-git#802]
The package strips binaries by default on it's own this breaks -debug packages.

In general interfering with makepkg's settings doesn't sound like a good idea.

**Comment by Thaodan** [comment]
For that you can options=(!strip), strip yourself and makepkg will not strip, 
no need for extra logic.

You should probably figure out why it breaks and override STRIP and pass the 
needed options if the bug isn't on makepkg.

**Comment by Tk-Glitch** [comment]
I couldn't reproduce the issue on my machine. `options=(strip)` worked fine for me and most users for years. But sometimes I had reports of that same breakage I couldn't explain until we figured it out in the linked issue.
We are passing `!strip` when `_pkg_strip` isn't enabled. `!strip` doesn't even work btw, because wine will strip on make install anyway to begin with (and with or without it, makepkg reports package stripping, but that's another problem).

So we could just pass `!strip` globally at this point and leave it to the `_pkg_strip` option.
