### ISSUE TITLE
[Question] Does Proton tkg contain DXVK async?

### ISSUE THREAD

**Issue by begin-theadventure** [Frogging-Family/wine-tkg-git#807]
Does Proton Tkg contain DXVK async from default like Proton GE?

**Comment by Tk-Glitch** [comment]
Short version: it's optionally available.

Longer version: proton-tkg uses our `https://github.com/Frogging-Family/dxvk-tools` to build its dxvk and the async pipeline compiler is a toggle option in the .cfg. You can use its external config feature to enforce your own settings through `$HOME/.config/frogminer/updxvk.cfg`, async included.

Since it tends to break pretty often + is unsafe + is now obsoleted for Nvidia users on current dxvk git (and the code making it obsolete is reverted by the async patch), we can't decently enable it by default. But it's there if someone wants it.

**Comment by begin-theadventure** [comment]
Thanks for the response.
