### ISSUE TITLE
[Proton-tkg] Error `fatal: could not create work tree dir 'openvr': File exists`

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#818]
```make
fatal: could not create work tree dir 'openvr': File exists
/home/neko-san/wine-tkg-git/proton-tkg/proton-tkg.sh: line 162: cd: openvr: No such file or directory
```
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/9227855/proton-tkg.log)

[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9227858/proton-tkg.cfg.txt)

**Comment by Tk-Glitch** [comment]
Your log shows other issues, notably with `gitlab.freedesktop.org` returning 504 (which breaks quite a few things afterwards). I assume the issue will vanish when the servers are back to a working state.
That "dir" should be a symlink (recreated on each build) to the corresponding external-resources subdir that you can check by yourself.

**Comment by ThisNekoGuy** [comment]
> That "dir" should be a symlink (recreated on each build) to the corresponding external-resources subdir that you can check by yourself.

I deleted the entire project folder and re-cloned before submitting the issue; I'm sure you're probably right (I was about to fall asleep just now), but wanted to make you aware that it wasn't because I touched anything there (also isn't the first time I've had this issue before but it happens occasionally)

**Comment by Tk-Glitch** [comment]
Oh no worries about that. I'll ask about what you could have done to break it in such case, but here it's a pretty hot path that anyone building proton-tkg will take, so the likely problem is freedesktop's gitlab repo being inaccessible, since we're not handling such cases and the script will attempt to continue nonetheless. Adding some opportunities for the script to exit on such breaking points would be useful :P

**Comment by Tk-Glitch** [comment]
I switched to the github mirror preemptively to lower the frequency of such an issue. It should be fixed also.
