### ISSUE TITLE
Separated folder for the 32bits and 64bits version when building on Gentoo. Why?

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/wine-tkg-git#878]
When compiling on Gentoo, we end up being with separated folders for x32 and x64 version. Is there a way to end up with the same structure when compiling on Arch?

**Comment by Tk-Glitch** [comment]
I'll need more details regarding dir hierarchy and naming as I'm not aware of a discrepancy here, and it also shouldn't exist.

**Comment by gardotd426** [comment]
This may not be a "proper" workaround, but regardless of whether you're trying to build wine-tkg or proton-tkg, you can simply specify the completed build directory (where the completed build will go), and then copy it to /opt or wherever else using sudo.

For example, I use wine-tkg-git that I build myself for all my lutris needs.  But I might need it for something else, so in `wine-tkg-git/wine-tkg-git/customization.cfg`, under `_nomakepkg_prefix_path=`, I have `_nomakepkg_prefix_path="/home/matt/winebuilds"`. So my winebuilds directory contains all my completed builds. I've been using this build system for like 2+ years (since way before it moved to the frogging-family repo), so the list is huge, but here's a snippet of `ls ~/winebuilds`: 

```
wine-tkg-staging-fsync-git-6.10.r1.gdaec2e36
wine-tkg-staging-fsync-git-6.16.r2.g4b48df50
wine-tkg-staging-fsync-git-6.17.r1.gad56d6b3
wine-tkg-staging-fsync-git-6.18.r10.gdbf2d00a
wine-tkg-staging-fsync-git-6.19.r1.g5e9626af
wine-tkg-staging-fsync-git-6.20.r10.gdf26057d
wine-tkg-staging-fsync-git-6.21.r0.g63c3baa9
wine-tkg-staging-fsync-git-6.21.r11.gd3d93cfa
wine-tkg-staging-fsync-git-6.22.r5.gedb34171
wine-tkg-staging-fsync-git-6.23.r0.g82e4617d
wine-tkg-staging-fsync-git-6.23.r1.ga2fcffc1
```

Then because I don't want to waste unneeded space, I just run (for example, I'll use the first build listed): `ln -s ~/winebuilds/wine-tkg-staging-fsync-git-6.10.r1.gdaec2e36 ~/.local/share/lutris/runners/wine/wine-tkg-git-6.10`. And bob's your uncle. I can now have that build in Lutris, and select it without any headache. I can place it in multiple locations, so for you, I could just run `sudo ln -s ~/winebuilds/<wineversion> /opt/<wherever>`

This is what I believe the actual logical and proper way to do this is, regardless of what the "Linux/UNIX/whatever-the-hell *proper*" method would be. But it's definitely not using sudo to run the script.

**Comment by gardotd426** [comment]
Honestly, putting the build in /opt sounds completely pointless to me. There's no reason to ever need a special wine build for your system wine. Because any program you'd need it for can just use the list of available wine builds you give it (lutris has it's runners/wine directory, I believe bottles has something similar, as does Heroic).

**Comment by rizzini** [comment]
> Honestly, putting the build in /opt sounds completely pointless to me. There's no reason to ever need a special wine build for your system wine. Because any program you'd need it for can just use the list of available wine builds you give it (lutris has it's runners/wine directory, I believe bottles has something similar, as does Heroic).

I'm sorry, but I didn't ask your opinion on that. Yeah, I remember you from Reddit.. You're the most obnoxious person I've ever met online. Please, stop engaging in my comments, wherever they might be.
