### ISSUE TITLE
misc: is it possible to see what patches are applied?

### ISSUE THREAD

**Issue by wael444** [Frogging-Family/wine-tkg-git#925]
this is mostly for miscellanous reasons such as self-compiling wine with select patches.

is it currently possible or is there a way to see what patches the wine tkg build applies to the wine build? like a list of what patches has been applied.

since some patches fail, is it possible to instead just simply get the list without applying and quit?

**Comment by wael444** [comment]
this is also mainly because i want to self-package wine to my distribution, but without using wine-tkg-git explicitly, and rather the wine source.

```
 -> Changing wine HEAD to the wine-staging base commit...
 -> Using patchinstall.sh --upstream-commit
HEAD is now at 772badd0d7f Release 8.0-rc1.
realpath: -Lm: No such file or directory
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```

**Comment by Tk-Glitch** [comment]
> since some patches fail
The failing patches should be reported as that *should* be fixed. I have no failing patch on my end against current Valve and upstream based, but all combinations of patches aren't tested as there are so many. Please report the failures.

Regarding your question, the list isn't currently pre-processed so you can't get a list of the patches that will be applied before they actually are. The logic is triggered at patch application since there are many inter-dependencies and dynamic application or even on-demand string manipulation involved. Options you select might be temporarily disabled due to upstream changes or get a hotfix due to a regression as well so while your config file allow for build reproduction, it cannot be used to know beforehand what will or will not be applied.

Regarding your log:
```
 -> Changing wine HEAD to the wine-staging base commit...
 -> Using patchinstall.sh --upstream-commit
HEAD is now at 772badd0d7f Release 8.0-rc1.
realpath: -Lm: No such file or directory
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```
There seems to be an issue with your `realpath` binary. GNU's `realpath` recognizes those flags so you're probably using an alternative one like busybox's, which is an extremely simplified version that only takes a file as argument with zero option.

I guess we could disabled community patches entirely when such a `realpath` binary is used and add a warning about it.

**Comment by Tk-Glitch** [comment]
It doesn't seem to immediately explode with busybox realpath so I'll add a check and a warning while attempting to use it anyway

**Comment by wael444** [comment]
> It doesn't seem to immediately explode with busybox realpath

```
BusyBox v1.35.0 (2022-11-28 14:51:39 UTC) multi-call binary.

Usage: realpath FILE...

Print absolute pathnames of FILEs
```

**Comment by Tk-Glitch** [comment]
So, yeah, busybox

**Comment by Tk-Glitch** [comment]
Please let me know how it goes after our small change above. It *should* work with busybox's realpath unless the path is **speshul**, and move on to the actual patch application step.

**Comment by wael444** [comment]
```
When you are ready, press enter to continue.
 -> No _LOCAL_PRESET set in .cfg. Please select your desired base (or hit enter for default) :
 ==> WARNING: ! "mainline" and "staging" options will make clean & untouched wine and wine-staging builds, ignoring your .cfg settings !
 ==> WARNING: ! "valve" profiles will use Valve proton wine trees instead of upstream, ignoring many incompatibble .cfg settings !
 ==> WARNING: ! "default-tkg" profile will use the main customization.cfg and wine-tkg-profiles/advanced-customization.cfg files !
 ->   0 - default-tkg
 ->   1 - mainline
 ->   2 - protonified
 ->   3 - staging
 ->   4 - valve
 ->   5 - valve-exp-bleeding
 ->   6 - other & legacy
  choice [0-6]: 
 -> Using staging patchset
 -> Using fsync patchset
 -> Cloning and preparing sources... Please be patient.
 -> Cleaning wine-staging source code tree...
 -> Cleaning wine source code tree...
 -> Changing wine HEAD to the wine-staging base commit...
 -> Using patchinstall.sh --upstream-commit
HEAD is now at ccdef80543f bcrypt: Do not error out for GNUTLS_ECC_CURVE_SECP384R1 in key_export_ecc().
 ==> WARNING: Detected non-GNU realpath (busybox?), please disable community patches in case of issues
 ==> WARNING: Hotfix: Fix for Riot Client updates
 ==> WARNING: Hotfix: Bcrypt fixes for RDR2
 ==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
 ==> WARNING: Hotfix: Fixup for Battle.net failing with a Qt error
 ==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
 -> cherry picking...
 -> Hotfixing...
 -> Applying steam.patch
 -> Applying CSMT-toggle.patch
 -> Applying wine-staging patches... 
     Staging overrides used, if any: 
 ==> ERROR: Patch application has failed. The error was logged to /home/wael/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> To use the last known good mainline version, please set _plain_version="" in your .cfg
 -> To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```

**Comment by Tk-Glitch** [comment]
Please attach your `/home/wael/wine-tkg-git/wine-tkg-git/prepare.log`

**Comment by wael444** [comment]
was missing automake and autoconf stuff, should probably have a check for that

**Comment by wael444** [comment]
yep works

**Comment by Tk-Glitch** [comment]
> was missing automake and autoconf stuff, should probably have a check for that

We have but unless you're on a pacman distro and running `makepkg -s` you'll need to manually enable it through the following config option:
```
# Set to the distro of your choice to attempt dependency resolution. Valid options are "debuntu" (for debian, ubuntu and similar), "fedora" or "archlinux".
_nomakepkg_dep_resolution_distro=""
```
It's kinda discouraged to attempt building multilib wine on Ubuntu or variants due to extremely poor multilib support, but most other distros should be alright.

I'm glad you got things to work :)

**Comment by wael444** [comment]
IMO, you shouldn't check for dependencies via package managers. you can check them with file paths (eg. `/usr/lib32/bullshit.so.9.9.9`) or with `pkgconfig`.

**Comment by Tk-Glitch** [comment]
> IMO, you shouldn't check for dependencies via package managers. you can check them with file paths (eg. `/usr/lib32/bullshit.so.9.9.9`) or with `pkgconfig`.

That was the initial idea, but long story short we ended up only doing it for very specific packages on very specific distros because pkgconfig is frogged on many distros with some packages. Recently gstreamer situation broke on Fedora, and there is a long list of broken packages on Ubuntu and Debian which tend to get worse instead of getting fixed as time passes. Add the paths discrepancy between distros in the mix and the package manager became the de-facto "more robust" approach for us.

I'm not fully satisfied with this tbh but it's not *terrible* either for our usecase. Wine's 32on64 will hopefully make things simpler in the near future.

**Comment by wael444** [comment]
off-topic:
https://termbin.com/72yev

how do i fix this compilation error? im trying natively patching wine only with the fsync patches without using the wine tkg build system, and this works just fine in it...

**Comment by wael444** [comment]
i should also probably close this issue since the original topic is 'solved'
