### ISSUE TITLE
auto builds for ubuntu failing

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/wine-tkg-git#926]
i noticed that the Wine Ubuntu CI & Proton nopackage Ubuntu CI & Wine Valve exp bleeding edge CI all seem to be failing for the auto build system. 

is there any way this can be fixed? i would like to download a newer version of these and really don't feel like setting up my system to build them. debian doesnt play nice with dual archs (i386 & amd64) for compiling.

**Comment by Tk-Glitch** [comment]
The bug is here: https://bugs.launchpad.net/ubuntu/+source/krb5/+bug/1980494

Ubuntu loves to break their own packages every few weeks. I suppose we could get rid of krb5 for the 32-bit side and call it a day for a while. It *will* break stuff but it's either that or nothing so..

Getting rid of Ubuntu is the most sensible thing to do imho.

**Comment by Tk-Glitch** [comment]
The CI will be able to succeed again with https://github.com/Frogging-Family/wine-tkg-git/commit/c0ee347e3ebc48b12bf49429c311bf99b3cce801. No more 32-bit krb5 support though, as explained above.

**Comment by rchris494** [comment]
thanks!
