### ISSUE TITLE
Proton-Tkg script does not use desired branch when cloning using Experimental Bleeding Edge, Experimental, or Proton profiles. Defaults to Experimental 8.0.

### ISSUE THREAD

**Issue by Glitch1441** [Frogging-Family/wine-tkg-git#997]
I have the following set in my `advanced-customization.cfg`:

`_proton_branch="experimental_7.0"`

Yet I get the following version as my branch, it seems:

`origin/experimental_8.0`

As per the below screenshot:
![2023-04-30T22:42:57,828601900+08:00](https://user-images.githubusercontent.com/110949634/235359368-20f04a24-8398-4fb1-955e-b2f1afc9592c.png)

**Comment by Glitch1441** [comment]
Am I reading any of the output wrong? Does the line` branch 'experimental_8.0' set up to track 'origin/experimental_8.0' ` mean that it's using the wrong proton branch or a wine branch?

**Comment by gardotd426** [comment]
This isn't a bug, it's user error. 

![image](https://user-images.githubusercontent.com/54234607/235816769-55fdafcd-2cc8-490e-bb6d-70ad7f3bd592.png)

you have `valve-exp-bleeding` as the `LOCAL_PRESET=` in your `customization.cfg`/`proton-tkg.cfg` file: `_LOCAL_PRESET="valve-exp-bleeding"` 

Which results in exactly what the terminal output you screenshotted says: "`Preset configuration valve-exp-bleeding will be used to override customization.cfg values`"

And the contents of `wine-tkg-git/wine-tkg-profiles/wine-tkg-valve-exp-bleeding.cfg`?:

```
# 'Wine-to-rule-them-all' - Wine-TkG config file
# Proton experimental - Bleeding Edge

_PKGNAME_OVERRIDE="valve-exp-bleeding"

_custom_wine_source="https://github.com/ValveSoftware/wine.git"
_plain_version="experimental_8.0"
_proton_branch="experimental_8.0"
_use_staging="false"
#_staging_version="e9f69afcab7a6143abb54854945bdbf7f091c60c"

# Optionally set a bleeding edge tag - Leave empty to use latest bleeding edge
_bleeding_tag=""

_CSMT_toggle="false"
_GLSL_toggle="false"
_lol920_fix="false"

_NOINITIALPROMPT="true"
_user_patches="true"
_user_patches_no_confirm="true"
```

`_LOCAL_PRESET="experimental_8.0"`

And:

`_plain_version="experimental_8.0`

If you don't want to build against:

1. Current Valve Proton tree (currently `proton_8.0`)
2. Current Valve Proton Experimental tree (`experimental_8.0`)
3. Current Valve Proton Experimental Bleeding Edge tree

Then you have to make sure `_LOCAL_PRESET` says `_LOCAL_PRESET="none"`. 

And that's it. You won't see a branch specified in the terminal output because `wine-tkg-git`/`proton-tkg` use upstream Wine/Wine Staging unless you force a different Wine source repo in the config. So you'll be building Proton using Valve's repo for everything except for the Wine build. 

Also, `experimental_7.0` is dead, so trying to build on it is completely pointless. There won't be any more 7.0 Proton Experimental, because Experimental is on 8.0 now. You need to change your Proton branch. `experimental_7.0` hasn't been updated in over 2 months, and it won't be updated anymore. You probably can't even build `proton-tkg` using `experimental_7.0` anymore. I don't know why you need to build a specific `proton-tkg` but also force it to 7.0, but I can just about guarantee that you don't *actually* need to be doing that. If you need a 7.X build, use Proton GE. Proton TKG is for creating builds using the latest code.

**Comment by Glitch1441** [comment]
> This isn't a bug, it's user error.
> 
> ![image](https://user-images.githubusercontent.com/54234607/235816769-55fdafcd-2cc8-490e-bb6d-70ad7f3bd592.png)
> 
> you have `valve-exp-bleeding` as the `LOCAL_PRESET=` in your `customization.cfg`/`proton-tkg.cfg` file: `_LOCAL_PRESET="valve-exp-bleeding"`
> 
> Which results in exactly what the terminal output you screenshotted says: "`Preset configuration valve-exp-bleeding will be used to override customization.cfg values`"
> 
> And the contents of `wine-tkg-git/wine-tkg-profiles/wine-tkg-valve-exp-bleeding.cfg`?:
> 
> ```
> # 'Wine-to-rule-them-all' - Wine-TkG config file
> # Proton experimental - Bleeding Edge
> 
> _PKGNAME_OVERRIDE="valve-exp-bleeding"
> 
> _custom_wine_source="https://github.com/ValveSoftware/wine.git"
> _plain_version="experimental_8.0"
> _proton_branch="experimental_8.0"
> _use_staging="false"
> #_staging_version="e9f69afcab7a6143abb54854945bdbf7f091c60c"
> 
> # Optionally set a bleeding edge tag - Leave empty to use latest bleeding edge
> _bleeding_tag=""
> 
> _CSMT_toggle="false"
> _GLSL_toggle="false"
> _lol920_fix="false"
> 
> _NOINITIALPROMPT="true"
> _user_patches="true"
> _user_patches_no_confirm="true"
> ```
> 
> `_LOCAL_PRESET="experimental_8.0"`
> 
> And:
> 
> `_plain_version="experimental_8.0`
> 
> If you don't want to build against:
> 
> 1. Current Valve Proton tree (currently `proton_8.0`)
> 2. Current Valve Proton Experimental tree (`experimental_8.0`)
> 3. Current Valve Proton Experimental Bleeding Edge tree
> 
> Then you have to make sure `_LOCAL_PRESET` says `_LOCAL_PRESET="none"`.
> 
> And that's it. You won't see a branch specified in the terminal output because `wine-tkg-git`/`proton-tkg` use upstream Wine/Wine Staging unless you force a different Wine source repo in the config. So you'll be building Proton using Valve's repo for everything except for the Wine build.
> 
> Also, `experimental_7.0` is dead, so trying to build on it is completely pointless. There won't be any more 7.0 Proton Experimental, because Experimental is on 8.0 now. You need to change your Proton branch. `experimental_7.0` hasn't been updated in over 2 months, and it won't be updated anymore. You probably can't even build `proton-tkg` using `experimental_7.0` anymore. I don't know why you need to build a specific `proton-tkg` but also force it to 7.0, but I can just about guarantee that you don't _actually_ need to be doing that. If you need a 7.X build, use Proton GE. Proton TKG is for creating builds using the latest code.

Actually, `experimental_7.0` was the default in `advanced-customization.cfg` iirc. I changed it to use `experimental_8.0 ` in the config and it still does not build. That's why I posted this issue, so perhaps you might have misunderstood?

**Comment by Glitch1441** [comment]
Ah wait. I get it now. It may very well be user error. I misread the terminal output I believe in all of this confusion. My apologies. Allow me to close this.
